local mod = get_mod("MourningstarWaitingGames")

return {
	mod_name        = { en = "Mourningstar Waiting Games" },
	mod_description = { en = "Open your auspex to play fourteen games, including Penitent Purge, Noosphere Breach, Battle Chess, Minesweeper, Solitaire, Hearts, SkiFree and Breakout, in the Mourningstar or Meat Grinder. Press F11 to start." },

	enable_tetris           = { en = "Enable Games" },
	enable_tetris_tooltip   = { en = "Master switch for the minigames." },
	game_type_tetris        = { en = "Tetris" },
	game_type_invaders      = { en = "Space Invaders" },
	game_type_quiz          = { en = "Warhammer 40k Quiz" },
		game_type_snake         = { en = "Snake" },
		game_type_pong          = { en = "Pong" },
		game_type_asteroids     = { en = "Asteroids" },
		game_type_raycaster     = { en = "Penitent Purge" },
		game_type_noosphere     = { en = "Noosphere Breach" },
		game_type_minesweeper   = { en = "Minesweeper" },
		game_type_solitaire     = { en = "Solitaire" },
		game_type_hearts        = { en = "Hearts" },
		game_type_skifree       = { en = "SkiFree" },
		game_type_breakout      = { en = "Breakout" },
		game_type_battlechess   = { en = "Battle Chess" },
	game_toggle_key         = { en = "Open Game Auspex" },
	game_toggle_key_tooltip = { en = "Open or close the game selector. Press it during a game to return to the selector." },
	tetris_not_allowed      = { en = "Games can only be played in the Mourningstar or Meat Grinder." },
	selector_title          = { en = "MOURNINGSTAR WAITING GAMES" },
	selector_subtitle       = { en = "SELECT AUSPEX PROGRAM" },
	selector_controls       = { en = "WASD / Arrows / Stick Select   Click / Enter / Space / E Launch   Esc Close" },
	selector_status         = { en = "14 PROGRAMS ONLINE" },
	selector_desc_tetris    = { en = "Stack and clear" },
	selector_desc_invaders  = { en = "Defend the sector" },
	selector_desc_quiz      = { en = "Test forbidden lore" },
	selector_desc_snake     = { en = "Grow and survive" },
	selector_desc_pong      = { en = "Outplay the machine" },
	selector_desc_asteroids = { en = "Survive the void" },
	selector_desc_raycaster = { en = "Raid the reliquary" },
	selector_desc_noosphere = { en = "Purge the noosphere" },
	selector_desc_minesweeper = { en = "Clear the minefield" },
	selector_desc_solitaire = { en = "Klondike patience" },
	selector_desc_hearts    = { en = "Dodge the Queen" },
	selector_desc_skifree   = { en = "Beware the Yeti" },
	selector_desc_breakout  = { en = "Clear the wall" },
	selector_desc_battlechess = { en = "Checkmate, violently" },

	tetris_controls     = { en = "A/D or Left/Right Move   S/Down Drop   W/Up Hard Drop   E/Q Rotate   R Hold" },
	invaders_controls   = { en = "A/D or Left/Right Move   LClick Fire   Esc Menu" },
	quiz_controls       = { en = "W/S or Up/Down Select   LClick Confirm   Esc Menu" },
	snake_controls      = { en = "WASD or Arrows Direction   Esc Menu" },
		pong_controls       = { en = "W/S or Up/Down Paddle   Esc Menu" },
		asteroids_controls  = { en = "A/D or Left/Right Turn   W/Up Thrust   S/Down Brake   LClick Fire" },
		raycaster_controls  = { en = "WASD / Arrows Move   Mouse Look   LClick / Space / Shift Dash   Esc Menu" },
		noosphere_controls  = { en = "WASD / Arrows Move   Mouse / Right Stick Aim   LClick / Trigger Fire   Space / Shift Dash" },

	tetris_highscore     = { en = "Best:" },
	invaders_highscore   = { en = "Best:" },
	quiz_highscore       = { en = "Best:" },
	snake_highscore      = { en = "Best:" },
		pong_highscore       = { en = "Best:" },
		asteroids_highscore  = { en = "Best:" },
		raycaster_highscore  = { en = "Best:" },
		noosphere_highscore  = { en = "Best:" },
		minesweeper_highscore = { en = "Best:" },
		solitaire_highscore  = { en = "Best:" },
		hearts_highscore     = { en = "Wins:" },
		skifree_highscore    = { en = "Best:" },
		breakout_highscore   = { en = "Best:" },
		battlechess_highscore = { en = "Wins:" },
	}
