local math_random = math.random

local ALL_QUESTIONS = {
	{ q = "Which Primarch betrayed the Emperor and started the Horus Heresy?",
	  a = { "Leman Russ", "Sanguinius", "Horus Lupercal", "Lion El'Jonson" }, correct = 2 },
	{ q = "What was the name of Horus's Legion before the Heresy?",
	  a = { "Death Guard", "Sons of Horus / Luna Wolves", "World Eaters", "Emperor's Children" }, correct = 1 },
	{ q = "On which planet did the Horus Heresy begin with the Drop Site Massacre?",
	  a = { "Calth", "Isstvan V", "Terra", "Prospero" }, correct = 1 },
	{ q = "Which Primarch is known as the 'Angel' and led the Blood Angels?",
	  a = { "Fulgrim", "Konrad Curze", "Sanguinius", "Vulkan" }, correct = 2 },
	{ q = "Which Legion was decimated by the Space Wolves at the Burning of Prospero?",
	  a = { "Thousand Sons", "Word Bearers", "Iron Warriors", "Night Lords" }, correct = 0 },
	{ q = "Who killed Sanguinius during the final battle on the Vengeful Spirit?",
	  a = { "Abaddon the Despoiler", "Horus", "Kharn the Betrayer", "Erebus" }, correct = 1 },
	{ q = "Which Primarch was known for his tactical genius and wrote the Codex Astartes?",
	  a = { "Roboute Guilliman", "Ferrus Manus", "Jaghatai Khan", "Corax" }, correct = 0 },
	{ q = "What was the name of the Imperial Fists' homeworld?",
	  a = { "Macragge", "Inwit", "Terra (Earth)", "Chogoris" }, correct = 1 },
	{ q = "Which Primarch was entrusted with overseeing the construction of the Imperial Palace?",
	  a = { "Perturabo", "Dorn", "Alpharius", "Lorgar" }, correct = 1 },
	{ q = "What was the name of the weapon used by the Emperor to strike down Horus?",
	  a = { "The Sword of the Emperor", "The Anathame", "The Talon of Horus", "A psychic blast that erased his soul" }, correct = 3 },

	{ q = "What is the primary role of the Adeptus Astartes (Space Marines)?",
	  a = { "Galactic tax collection and economic oversight", "Elite superhuman shock troops deployed for the most critical battles", "Agricultural management of Imperial agri-worlds", "Diplomatic envoys to xenos civilizations" }, correct = 1 },
	{ q = "What is the Astra Militarum more commonly known as?",
	  a = { "The Imperial Guard", "The Navy", "The Inquisition", "The Frateris Militia" }, correct = 0 },
	{ q = "Which organisation within the Imperium hunts witches, mutants and xenos?",
	  a = { "The Administratum", "The Inquisition", "The Adeptus Mechanicus", "The Navis Nobilite" }, correct = 1 },
	{ q = "What is the Machine God worshipped by the Adeptus Mechanicus?",
	  a = { "The Emperor", "The Omnissiah", "Gork and Mork", "Tzeentch" }, correct = 1 },
	{ q = "Which Imperial organisation is responsible for interstellar communication via the Astronomican?",
	  a = { "The Adeptus Astra Telepathica", "The Imperial Navy", "The Officio Assassinorum", "The Ecclesiarchy" }, correct = 0 },
	{ q = "What is a 'Throne' in Imperial terminology?",
	  a = { "An ornate piece of furniture reserved for planetary governors", "The standard currency of the Imperium of Man", "A mid-level rank within the Imperial Guard hierarchy", "A light reconnaissance vehicle used by the Adeptus Arbites" }, correct = 1 },
	{ q = "Who leads the Ecclesiarchy, the state church of the Imperium?",
	  a = { "The Fabricator-General", "The Ecclesiarch", "The Lord Inquisitor", "The High Admiral" }, correct = 1 },
	{ q = "What is the purpose of the Black Ships?",
	  a = { "Covert naval warfare behind enemy lines using stealth technology", "Transporting unsanctioned psykers to Terra — to be Soul-bound or sacrificed to the Astronomican", "Piracy suppression patrols along unstable Warp routes", "Explorator missions charting uncharted regions beyond the Astronomican's light" }, correct = 1 },

	{ q = "Which Chaos God represents bloodshed, war and rage?",
	  a = { "Tzeentch", "Nurgle", "Khorne", "Slaanesh" }, correct = 2 },
	{ q = "Which Chaos God is associated with decay, disease and stagnation?",
	  a = { "Khorne", "Nurgle", "Slaanesh", "Tzeentch" }, correct = 1 },
	{ q = "Which Chaos God embodies change, trickery and sorcery?",
	  a = { "Slaanesh", "Khorne", "Nurgle", "Tzeentch" }, correct = 3 },
	{ q = "Which Chaos God was born from the fall of the Eldar?",
	  a = { "Khorne", "Slaanesh", "Tzeentch", "Nurgle" }, correct = 1 },
	{ q = "What is the name of the realm of Chaos?",
	  a = { "The Warp / The Immaterium", "The Webway", "The Halo Zone", "The Maelstrom" }, correct = 0 },
	{ q = "What are Daemon Princes?",
	  a = { "Warp entities spontaneously born from concentrated mortal emotion", "Once-mortal champions elevated to daemonhood by a Chaos God as a reward for service", "Possessed Space Marines whose bodies host a daemonic parasite", "Greater Daemons manifested from the essence of a single Chaos God" }, correct = 1 },

	{ q = "What caused the fall of the ancient Eldar civilisation?",
	  a = { "An Ork WAAAGH!", "A Necron uprising", "Their own hedonism created Slaanesh", "A Tyranid invasion" }, correct = 2 },
	{ q = "What is a Craftworld?",
	  a = { "A small Eldar strike craft used for hit-and-run attacks", "A continent-sized void-ship — a mobile world housing millions of Eldar souls", "A form of Wraithbone melee weapon", "A Chaos fortress orbiting the Eye of Terror" }, correct = 1 },
	{ q = "Who are the Ork gods?",
	  a = { "Khorne and Nurgle", "Gork and Mork", "The Twin Emperors", "Morkai and Fenris" }, correct = 1 },
	{ q = "What is a WAAAGH!?",
	  a = { "A fortified Ork settlement centred around a Mekboy workshop", "A massive interstellar Ork migration — billions of Orks swept into a single warpath", "An Ork Nob who has defeated enough rivals to lead a warband", "A heavy Ork artillery piece that fires looted tank shells" }, correct = 1 },
	{ q = "What is a 'Mekboy' among the Orks?",
	  a = { "A genetically encoded Ork Oddboy who instinctively builds and repairs complex technology", "A Painboy specializing in battlefield surgery and bionic graftings", "A Runtherd who oversees Gretchin labour and squig-herding", "A Weirdboy attuned to the psychic WAAAGH! field" }, correct = 0 },
	{ q = "What are the Necrons?",
	  a = { "Ancient biological xenos who achieved transcendence through meditation", "A race of soulless machine-entities — once flesh, now living metal, seeking to reclaim the galaxy", "Warp-born spirits bound to ancient armour by Chaos sorcery", "Heavily mutated human colonists from the Dark Age of Technology" }, correct = 1 },
	{ q = "Which material are Necron bodies made of?",
	  a = { "Ceramite — the same bonded composite used in Astartes power armour", "Adamantium — the strongest metallic alloy known to the Imperium", "Necrodermis — self-repairing living metal that flows like liquid and hardens instantly", "Plasteel — a lightweight armoured polymer used in Imperial construction" }, correct = 2 },
	{ q = "What drives the Tyranids across the galaxy?",
	  a = { "A spiritual pilgrimage toward the Astronomican's light", "An insatiable genetic hunger — they strip entire systems of all organic matter", "Religious veneration of the Hive Mind as a deity", "Millennia-old vengeance against the Imperium for past defeats" }, correct = 1 },
	{ q = "What is a Hive Fleet?",
	  a = { "A single Tyranid bio-ship scouting ahead of the main swarm", "A colossal armada of millions of Tyranid organisms — a galaxy-consuming tendril of the Hive Mind", "A refugee flotilla fleeing a Tyranid-devoured system", "An Eldar war host mustered to counter a Tyranid incursion" }, correct = 1 },
	{ q = "Which race is known for its philosophy of the 'Greater Good'?",
	  a = { "The Eldar, who pursue a path of self-discipline", "The Tau — a collectivist ideology where individual sacrifice serves the many", "The Imperium, through its devotion to the Emperor", "The Leagues of Votann, guided by their Ancestor Cores" }, correct = 1 },
	{ q = "What are the Ethereals in Tau society?",
	  a = { "Tau Earth caste engineers who design pulse weaponry", "The mysterious ruling caste whose presence compels absolute obedience in all other Tau", "Tau Fire caste commanders leading hunter cadres", "Tau Water caste merchants overseeing interstellar trade" }, correct = 1 },
	{ q = "What is the Webway?",
	  a = { "A labyrinthine network of stable tunnels through the Warp — built by the Old Ones for safe travel", "An Imperial trade route connecting the Segmentum fortresses", "A Tyranid synapse communication system linking Hive Ships", "The Ork spiritual realm where Gork and Mork dwell" }, correct = 0 },

	{ q = "Which Primarch was resurrected and now leads the Imperium as Lord Regent?",
	  a = { "Lion El'Jonson", "Sanguinius", "Roboute Guilliman", "Ferrus Manus" }, correct = 2 },
	{ q = "Which Space Marine Chapter is known for the phrase 'For the Emperor!' and their black armour?",
	  a = { "Ultramarines", "Blood Angels", "Black Templars", "Space Wolves" }, correct = 2 },
	{ q = "What is Abaddon the Despoiler famous for?",
	  a = { "Defeating the Emperor", "Leading the Black Crusades from the Eye of Terror", "Creating the Space Marines", "Ruling the Tau" }, correct = 1 },
	{ q = "Who is the leader of the Space Wolves?",
	  a = { "Leman Russ (missing)", "Bjorn the Fell-Handed", "Logan Grimnar", "Ragnar Blackmane" }, correct = 2 },
	{ q = "What was the name of the First Space Marine Legion?",
	  a = { "Ultramarines", "Dark Angels", "Space Wolves", "Imperial Fists" }, correct = 1 },
	{ q = "Who is the most famous Imperial Commissar, known for his brutality?",
	  a = { "Ciaphas Cain", "Commissar Yarrick", "Ibram Gaunt", "Commissar Severina Raine" }, correct = 1 },
	{ q = "Which figure is known as the 'Avenging Son'?",
	  a = { "Lion El'Jonson", "Roboute Guilliman", "Sanguinius", "Corax" }, correct = 1 },
	{ q = "What is Inquisitor Gregor Eisenhorn known for?",
	  a = { "Becoming a Daemon Prince", "His unorthodox methods and use of radical tools against Chaos", "Leading the Black Templars", "Designing the Golden Throne" }, correct = 1 },

	{ q = "What is a Bolter?",
	  a = { "A lasgun variant used exclusively by planetary defence forces", "A .75 calibre self-propelled rocket grenade weapon — standard Astartes firearm", "A plasma-based sidearm issued to Guard sergeants", "A chain-driven melee weapon with adamantium teeth" }, correct = 1 },
	{ q = "What is a Dreadnought?",
	  a = { "A super-heavy assault tank with dual-mounted lascannons", "An armoured life-support sarcophagus carrying a mortally wounded Space Marine into battle", "A void-capable gunship used for planetary landings", "A fixed fortification housing a long-range missile battery" }, correct = 1 },
	{ q = "What is a Power Fist?",
	  a = { "A standard-issue laspistol with an extended power cell", "A heavy gauntlet sheathed in a disruption field — capable of crushing tank armour", "A fragmentation grenade with an enlarged blast radius", "A close-combat blade with a mono-molecular edge" }, correct = 1 },
	{ q = "What is the God-Engine of the Adeptus Mechanicus?",
	  a = { "An orbital defence platform guarding Mars", "A Titan — a colossal walking war-machine crewed by a Princeps and Moderati", "The Golden Throne's life-support regulation system", "A super-heavy tracked tank armed with a Volcano Cannon" }, correct = 1 },
	{ q = "What is a Terminator suit?",
	  a = { "A sealed environment suit worn by fighter pilots during void operations", "Heavily reinforced Tactical Dreadnought Armour — used for boarding actions and tunnel fighting", "An automated combat servitor chassis for frontline deployment", "A ceremonial uniform worn by Imperial Navy flag officers" }, correct = 1 },
	{ q = "What is the primary purpose of the Imperial Navy?",
	  a = { "Exclusive troop transport between forge worlds", "Void warfare in deep space — fleet engagements, orbital bombardments, and system defence", "Planetary exploration and charting of unknown regions", "Diplomatic escort missions for Rogue Traders" }, correct = 1 },

	{ q = "What is the name of the Emperor's personal bodyguard?",
	  a = { "The Adeptus Custodes", "The Adeptus Astartes", "The Solar Auxilia", "The Lucifer Blacks" }, correct = 0 },
	{ q = "How long did the Great Crusade last?",
	  a = { "~100 years", "~200 years", "~500 years", "~1000 years" }, correct = 1 },
	{ q = "What was the fate of the two missing Primarchs (II and XI)?",
	  a = { "Killed by Horus", "Lost in the Warp", "Stricken from all records — fate unknown", "Defected to the Tau" }, correct = 2 },
	{ q = "Which treaty merged the Mechanicum with the Imperium?",
	  a = { "The Treaty of Mars", "The Edict of Nikaea", "The Council of Terra", "The Treaty of Olympus Mons" }, correct = 0 },
	{ q = "Which gene-crafted super-soldiers preceded the Space Marines?",
	  a = { "The Lucifer Blacks", "The Thunder Warriors", "The Solar Auxilia", "The Adeptus Custodes" }, correct = 1 },
	{ q = "What happened to the Thunder Warriors after the Unification Wars?",
	  a = { "Became Space Marines", "Were culled — exterminated by the Custodes", "Joined Chaos", "Became the Imperial Guard" }, correct = 1 },
	{ q = "What is the name of the Imperial Palace's innermost sanctum?",
	  a = { "The Sanctum Imperialis", "The Eternity Gate", "The Lion's Gate", "The Golden Throne Room" }, correct = 0 },
	{ q = "What substance do the Adeptus Custodes use that makes them superior to Space Marines?",
	  a = { "Gene-seed harvested from the Primarchs themselves", "The Emperor's own bio-alchemy — individually crafted at a molecular level", "Necrodermis grafts bonded directly to the skeletal structure", "Warp-infused serum extracted from the Astronomican's light" }, correct = 1 },

	{ q = "What is the gene-seed of a Space Marine?",
	  a = { "A bionic organ implanted during the final phase of initiation", "Genetic material grown from a Primarch's DNA — used to create new Space Marine organs", "A combat stimulant injected before each deployment", "A psychic implant that enhances the Marine's connection to the Warp" }, correct = 1 },
	{ q = "Which Legion was known for siege warfare and attrition?",
	  a = { "Imperial Fists", "Iron Warriors", "Death Guard", "World Eaters" }, correct = 1 },
	{ q = "Which Legion fell to the Blood God Khorne?",
	  a = { "Emperor's Children", "World Eaters", "Death Guard", "Night Lords" }, correct = 1 },
	{ q = "Which Legion fell to Nurgle, the Plague God?",
	  a = { "Iron Warriors", "World Eaters", "Death Guard", "Word Bearers" }, correct = 2 },
	{ q = "Which Legion serves Tzeentch, the Changer of Ways?",
	  a = { "Alpha Legion", "Thousand Sons", "Night Lords", "Iron Warriors" }, correct = 1 },
	{ q = "Which Legion serves Slaanesh, the Prince of Pleasure?",
	  a = { "Sons of Horus", "World Eaters", "Emperor's Children", "Word Bearers" }, correct = 2 },
	{ q = "Which Legion was the first to be corrupted by Chaos (through Erebus)?",
	  a = { "Sons of Horus", "Word Bearers", "Alpha Legion", "Night Lords" }, correct = 1 },
	{ q = "What are the two organs that make a Space Marine? (the 2 most iconic)",
	  a = { "Progenoid glands — the gene-seed", "Black Carapace and Progenoid Glands", "Occulobe and Lyman's Ear", "Betcher's Gland and Omophagea" }, correct = 1 },
	{ q = "Which loyalist Chapter is known for its vampire-like flaw, the Red Thirst?",
	  a = { "Space Wolves", "Blood Angels", "Dark Angels", "White Scars" }, correct = 1 },
	{ q = "Which loyalist Chapter is famous for hunting the Fallen across the galaxy?",
	  a = { "Ultramarines", "Dark Angels", "Imperial Fists", "Raven Guard" }, correct = 1 },
	{ q = "Which loyalist Chapter are the 'Wolf-themed' warriors of Fenris?",
	  a = { "Luna Wolves", "White Scars", "Space Wolves", "Iron Wolves" }, correct = 2 },
	{ q = "What is the name of the Grey Knights' fortress-monastery on Titan?",
	  a = { "The Fang", "The Rock", "The Citadel of Titan", "The Phalanx" }, correct = 2 },

	{ q = "What is the name of the daemon world within the Eye of Terror where the Traitor Legions reside?",
	  a = { "Sortiarius", "Medrengard", "The Planet of the Sorcerers", "There are many — each Legion has its own" }, correct = 3 },
	{ q = "What are the Neverborn?",
	  a = { "Mutants", "Daemons — entities born of the Warp", "Psykers", "The Lost Primarchs" }, correct = 1 },
	{ q = "What is a Gellar Field used for?",
	  a = { "Planetary void shields against orbital bombardment", "A reality-stabilizing bubble that protects void-ships during Warp transit from daemonic incursion", "A containment field isolating rogue psykers during Black Ship transport", "An energy curtain shielding Titan reactors from meltdown" }, correct = 1 },
	{ q = "Who is the Architect of Fate?",
	  a = { "Magnus the Red", "Tzeentch", "Erebus", "Ahriman" }, correct = 1 },
	{ q = "Which Chaos God is the youngest?",
	  a = { "Khorne", "Nurgle", "Tzeentch", "Slaanesh" }, correct = 3 },
	{ q = "What is the Black Legion?",
	  a = { "A loyalist successor Chapter descended from the Imperial Fists", "Abaddon the Despoiler's unified Chaos warband — former Sons of Horus, now the largest Traitor force", "The Night Lords under a new identity after the death of Konrad Curze", "A Death Guard splinter fleet that broke from Mortarion's command" }, correct = 1 },
	{ q = "What is the name of Abaddon's daemon sword?",
	  a = { "The Anathame", "Drach'nyen", "The Black Blade", "Gorechild" }, correct = 1 },
	{ q = "What are the Obliterator Virus and the Techno-virus associated with?",
	  a = { "Nurgle's plague that rots flesh into a diseased slurry", "The Dark Mechanicum — a warp-based infection that melds flesh with weaponry into a living arsenal", "A Tyranid spore that rewrites host DNA into bioforms", "A Necron nanite plague that converts organic matter to living metal" }, correct = 1 },
	{ q = "Who is Kharn the Betrayer?",
	  a = { "A Word Bearers Dark Apostle who orchestrated the corruption of Lorgar", "The most feared mortal champion of Khorne — slaughterer of friend and foe alike across ten millennia", "A Death Guard Plague Marine known for spreading Nurgle's Rot", "The leader of the Black Legion during Abaddon's absence" }, correct = 1 },
	{ q = "What is the significance of the planet Cadia?",
	  a = { "It was the birthplace of the Emperor", "It guarded the only stable route out of the Eye of Terror — destroyed in the 13th Black Crusade", "It's the Tau homeworld", "It's the capital of Ultramar" }, correct = 1 },

	{ q = "What are the three major Ordos of the Inquisition?",
	  a = { "Ordo Machinum, Ordo Astra, Ordo Terra", "Ordo Malleus (daemons), Ordo Hereticus (heretics), Ordo Xenos (aliens)", "Ordo Militarum, Ordo Navis, Ordo Astartes", "Ordo Magistratum, Ordo Redactor, Ordo Tempestus" }, correct = 1 },
	{ q = "What is an Exterminatus?",
	  a = { "A diplomatic treaty ending hostilities between Imperial factions", "The sanctioned annihilation of an entire world's biosphere — a final sanction reserved for irredeemable corruption", "A Space Marine recruitment sweep across multiple hive cities", "A system-wide Warp storm triggered by an ancient archaeotech device" }, correct = 1 },
	{ q = "Which radical Inquisitor is famous for using daemonhosts?",
	  a = { "Inquisitor Coteaz", "Inquisitor Eisenhorn", "Inquisitor Greyfax", "Inquisitor Karamazov" }, correct = 1 },
	{ q = "What is the function of the Officio Assassinorum?",
	  a = { "Diplomatic negotiations", "Assassination of key Imperial enemies using specialized temples", "Policing the Adeptus Astartes", "Guarding the Emperor" }, correct = 1 },
	{ q = "What are the four major Assassin temples?",
	  a = { "Vindicare, Callidus, Eversor, Culexus", "Vindicare, Malleus, Hereticus, Xenos", "Callidus, Custodes, Culexus, Astartes", "Eversor, Mortis, Vindicare, Solar" }, correct = 0 },
	{ q = "What makes Culexus Assassins unique?",
	  a = { "They are Ogryns", "They are psychic blanks (Pariahs) — they emit no soul presence", "They use only plasma weapons", "They can fly" }, correct = 1 },
	{ q = "What does the Adeptus Arbites do?",
	  a = { "They are the Imperial police and enforcers of the Lex Imperialis", "They are diplomats", "They are religious leaders", "They manage warp travel" }, correct = 0 },
	{ q = "What are the High Lords of Terra?",
	  a = { "The twelve most powerful rulers of the Imperium who govern in the Emperor's name", "The Primarchs", "The Chapter Masters of the First Founding", "The leaders of the Inquisition" }, correct = 0 },

	{ q = "What is the Imperial Cult?",
	  a = { "A secret society", "The state religion — worship of the Emperor as a god", "A military doctrine", "A type of psyker training" }, correct = 1 },
	{ q = "What are the Sisters of Battle officially called?",
	  a = { "The Frateris Militia", "The Adepta Sororitas", "The Sisters of Silence", "The Orders Hospitaller" }, correct = 1 },
	{ q = "What was the Age of Apostasy?",
	  a = { "A Chaos invasion", "A period of civil war caused by the corrupt Ecclesiarch Goge Vandire", "The fall of the Eldar", "The Horus Heresy" }, correct = 1 },
	{ q = "Who is Saint Celestine?",
	  a = { "A Primarch", "A living saint of the Adepta Sororitas — she resurrects when killed", "A High Lord of Terra", "An Inquisitor" }, correct = 1 },
	{ q = "What is the Decree Passive?",
	  a = { "A trade agreement with the Tau", "The law that forbids the Ecclesiarchy from maintaining 'men under arms'", "A ban on psykers", "The treaty that ended the Horus Heresy" }, correct = 1 },

	{ q = "What is Commorragh?",
	  a = { "An Eldar Craftworld hidden in a dying star's corona", "A pocket-dimension Dark City within the Webway — home to the Drukhari and their endless depravity", "An Imperial fortress world guarding the Cadian Gate", "A Necron tomb world beneath a hollow planetary crust" }, correct = 1 },
	{ q = "Why do the Drukhari (Dark Eldar) inflict pain and suffering?",
	  a = { "Exclusively for entertainment and status within their kabals", "Slaanesh perpetually leeches their souls — they replenish them by feeding on the agony of others", "To empower Khorne with every act of violence they commit", "As a biological requirement to fuel their dark-matter starship engines" }, correct = 1 },
	{ q = "What are Incubi?",
	  a = { "Elite Drukhari warrior-bodyguards — disciplined killers trained in secret shrines, loyal only to their contract", "Grotesque flesh-constructs stitched together by Haemonculi", "Wych cult gladiators who fight in Commorragh's arenas for fame", "Drukhari pilots who command Razorwing jetfighters in realspace raids" }, correct = 0 },
	{ q = "What are Haemonculi?",
	  a = { "Drukhari flesh-crafters who can regrow a dead Eldar from a single cell — masters of pain and resurrection", "The ruling council of the largest Drukhari kabal in Commorragh", "Drukhari assassins who phase through solid matter using shadow arts", "Eldar spirit-seers who guide souls into the Infinity Circuit" }, correct = 0 },
	{ q = "What happens to a Drukhari who dies without being resurrected by a Haemonculus?",
	  a = { "They reincarnate", "Slaanesh devours their soul — true death", "They become a Wraithguard", "They join the Harlequins" }, correct = 1 },

	{ q = "How do Orks reproduce?",
	  a = { "Sexual reproduction between male and female Orks in spawning seasons", "Through released fungal spores that gestate underground into fully-formed Orks", "Cloning tanks maintained by Mekboys in hidden workshops", "Eggs laid in warm biomass by Ork brood-mothers" }, correct = 1 },
	{ q = "What is the WAAAGH! field?",
	  a = { "A void shield generated by Ork Weirdboyz during fleet engagements", "A psychic gestalt field — the collective belief of Orks that bends reality and makes their ramshackle technology work", "A localized Warp storm that follows large Ork migrations", "A telepathic communication network linking all Warbosses across the galaxy" }, correct = 1 },
	{ q = "What is a Warboss?",
	  a = { "An Ork chef", "The largest, strongest Ork leading a WAAAGH!", "A type of Ork vehicle", "An Ork medic" }, correct = 1 },
	{ q = "Who is Ghazghkull Mag Uruk Thraka?",
	  a = { "An Imperial commander", "The most powerful Ork Warboss — Prophet of Gork and Mork", "A Chaos Space Marine", "An Eldar Farseer" }, correct = 1 },
	{ q = "What 'color logic' do Orks believe in?",
	  a = { "Red vehicles move faster, purple is stealthy, yellow yields bigger explosions, blue is lucky", "All colours are equally sacred manifestations of Gork and Mork", "Only green has power — it is the colour of Ork skin and vitality", "Blue is the luckiest colour, worn exclusively by Nobz and Warbosses" }, correct = 0 },

	{ q = "What is the Silent King?",
	  a = { "The Emperor of Mankind", "Szarekh — the last and greatest ruler of the Necron race", "An Eldar god", "A Chaos Daemon" }, correct = 1 },
	{ q = "What are the C'tan?",
	  a = { "Necron foot soldiers armed with gauss flayers", "Ancient star-gods — beings of pure energy who consumed stars, shattered by the Necrons and now used as enslaved shards", "Tyranid synapse creatures that coordinate Hive Fleet movements", "Eldar deities who survived the Fall and now inhabit the Webway" }, correct = 1 },
	{ q = "What is a Necron Tomb World?",
	  a = { "A human cemetery planet maintained by the Ecclesiarchy", "A dormant planet where billions of Necrons slumber in stasis-crypts — awaiting awakening protocols", "A Tyranid hive where bio-mass is stored for digestion", "A Chaos fortress world within the Eye of Terror" }, correct = 1 },
	{ q = "What is Necron 'reanimation protocols'?",
	  a = { "A diplomatic negotiation framework used with alien species", "Self-repair nanite systems that reassemble fallen Necrons — they stand back up after being blown apart", "A targeting algorithm that prioritizes enemy commanders", "A Warp-based resurrection ritual conducted by Crypteks" }, correct = 1 },
	{ q = "Who is Trazyn the Infinite?",
	  a = { "A Necron Overlord who obsessively collects historical artifacts and living beings in stasis — curator of a galaxy-wide museum", "A Space Marine Chapter Master of the Ultramarines' 2nd Company", "A Chaos Sorcerer of the Thousand Sons who sought the Black Library", "An Imperial Guard General who defended Cadia during the 13th Black Crusade" }, correct = 0 },

	{ q = "What is the Hive Mind?",
	  a = { "The Emperor's psychic will", "The collective consciousness controlling all Tyranid organisms", "A Necron AI", "A Chaos God" }, correct = 1 },
	{ q = "What are Genestealer Cults?",
	  a = { "Secret Chaos-worshipping cells embedded in Imperial hive cities", "Hybrid infiltrators bred by Genestealers — they subvert planetary society from within to welcome a Hive Fleet", "Eldar religious sects that venerate the Phoenix Lords", "Imperial organizations charged with rooting out mutant populations" }, correct = 1 },
	{ q = "What is a Norn Queen?",
	  a = { "An Eldar goddess of fate and prophecy", "The bio-factory organism at the heart of a Hive Ship — it designs and spawns every Tyranid creature in the fleet", "A human planetary governor who surrendered to the Tyranids", "A Necron Phaeron who awakened to find their world consumed" }, correct = 1 },
	{ q = "What are Zoanthropes?",
	  a = { "Tyranid shock troops that swarm enemies in close combat", "Floating Tyranid psykers — their brains channel the Hive Mind's power into devastating Warp Blasts", "Tyranid scout organisms that infiltrate ahead of the main swarm", "Living transport organisms that carry smaller bioforms inside armoured sacs" }, correct = 1 },
	{ q = "What is the Shadow in the Warp?",
	  a = { "A Chaos ritual that cloaks fleet movements from Imperial detection", "The psychic interference cast by the Hive Mind — it drowns out all other Warp signals and drives psykers mad", "An Eldar prophecy foretelling the Rhana Dandra", "A Necron weapon that severs a being's connection to the Warp" }, correct = 1 },

	{ q = "What are the Tau castes?",
	  a = { "Fire (Shas — warriors), Earth (Fio — builders), Water (Por — diplomats), Air (Kor — pilots), Ethereal (Aun — leaders)", "Gold, Silver, Bronze, Iron, Platinum — representing social ranks", "Alpha, Beta, Gamma, Delta, Omega — assigned at birth by genetic screening", "Sun, Moon, Star, Void, Spirit — spiritual paths chosen during adolescence" }, correct = 0 },
	{ q = "What are Kroot?",
	  a = { "A Tau caste", "A mercenary alien race allied with the Tau — they eat their enemies to absorb genetic traits", "A type of Tau battlesuit", "A Chaos daemon" }, correct = 1 },
	{ q = "What is the Tau's FTL technology limitation?",
	  a = { "They rely on captured Imperial Navigators for Warp travel", "They lack true Warp drives — their early expansion used near-light-speed stasis ships, severely limiting their reach", "They require Necron inertialess drives traded through diplomacy", "They teleport between systems using Webway gates gifted by the Eldar" }, correct = 1 },
	{ q = "What is Commander Farsight known for?",
	  a = { "Leading the Ethereal caste's council on T'au", "Breaking from the Tau Empire to form the independent Farsight Enclaves — and wielding a life-draining xenos sword", "Commanding the Water caste's trade fleet across the Damocles Gulf", "Inventing the pulse rifle and standardizing Tau infantry equipment" }, correct = 1 },
	{ q = "What are Tau Battlesuits called?",
	  a = { "Dreadnoughts", "Crisis, Broadside, Riptide, and Stormsurge suits", "Terminator armour", "Knights" }, correct = 1 },

	{ q = "What is the standard-issue weapon of the Imperial Guard?",
	  a = { "The Bolter", "The M35 M-Galaxy Pattern Lasgun", "The Plasma Gun", "The Autogun" }, correct = 1 },
	{ q = "From which planet do the toughest survivalist Guardsmen hail?",
	  a = { "Terra — hardened by millennia of hive-gang warfare", "Catachan — a death world where every organism is lethally evolved to kill", "Ultramar — trained from youth in the Ultramar Auxilia", "Mars — cybernetically augmented forge world conscripts" }, correct = 1 },
	{ q = "What is the Regiment system of the Imperial Guard?",
	  a = { "All Guardsmen receive standardized training on a single forge world", "Regiments are raised from single worlds — each carries that world's culture, tactics, and uniform into battle", "Regiments are randomly mixed to prevent planetary loyalties from forming", "The Imperial Navy assigns Guardsmen to regiments based on aptitude testing" }, correct = 1 },
	{ q = "What is a Commissar's primary role?",
	  a = { "Logistics officer responsible for regimental supply lines", "Discipline enforcer and political officer — empowered to execute cowards and inspire loyalty through fear", "Tank commander of Leman Russ battle squadrons", "Diplomatic liaison between Imperial Guard and allied xenos forces" }, correct = 1 },
	{ q = "What was the Fall of Cadia?",
	  a = { "A minor skirmish", "The destruction of Cadia during the 13th Black Crusade — the planet broke apart", "A Tyranid invasion", "A Necron awakening" }, correct = 1 },
	{ q = "What are Ogryns?",
	  a = { "Heavy artillery platforms mounted on Chimera chassis", "Loyal abhuman shock troops — immensely strong, immensely tough, and immensely dim-witted", "A senior Space Marine rank between Sergeant and Captain", "A type of minor daemon bound into servitude by the Inquisition" }, correct = 1 },

	{ q = "What is a psyker?",
	  a = { "A soulless individual immune to Warp phenomena", "A human able to channel the Warp's power — a walking gateway to the Immaterium, feared and sanctioned", "A Space Marine specialized in void-combat operations", "A Necron construct designed to replicate living consciousness" }, correct = 1 },
	{ q = "What is the Astronomican?",
	  a = { "A planet-cracking weapon mounted on the Phalanx", "A psychic beacon of unimaginable power — generated by the Emperor's will, it guides all Imperial Warp travel", "An ancient void-ship discovered in the Halo Stars", "A treaty binding the Navigator Houses to the Imperium" }, correct = 1 },
	{ q = "What are Navigators?",
	  a = { "Ship pilots", "A sanctioned mutant caste with a third eye — the only ones who can guide ships through the Warp", "A type of Astartes", "Imperial Guard officers" }, correct = 1 },
	{ q = "What is the Warp?",
	  a = { "A physical dimension existing between star systems", "The Immaterium — a psychic mirror-realm of emotion and nightmare where the Chaos Gods dwell", "A form of xenos faster-than-light engine technology", "The Imperial designation for the empty void between galactic arms" }, correct = 1 },
	{ q = "What is the difference between a sanctioned and a rogue psyker?",
	  a = { "Sanctioned psykers are Soul-bound to the Emperor and legally permitted; rogues are unsanctioned and hunted as dangers to society", "There is no meaningful distinction — both are equally tolerated", "Rogue psykers are inherently more powerful and harder to control", "Sanctioned psykers exist only on Terra and are forbidden from leaving" }, correct = 0 },
	{ q = "What are the Sisters of Silence?",
	  a = { "Female Space Marines drawn from the Adepta Sororitas", "Null-maidens — psychic blanks whose very presence severs Warp connections and unravels daemons", "A non-combat medical order treating wounded Guardsmen", "Imperial Guard officers who command all-female regiments" }, correct = 1 },

	{ q = "What were the Men of Iron?",
	  a = { "Legendary human champions of the Age of Terra", "Sentient AI constructs that rebelled against mankind — their war helped end the Dark Age of Technology", "The first generation of Space Marines, later disbanded", "Ancient Eldar automata used during the War in Heaven" }, correct = 1 },
	{ q = "What caused the Age of Strife?",
	  a = { "A Chaos invasion from the Eye of Terror", "Warp storms isolated human worlds + AI rebellion + psyker emergence — near-total collapse", "The Tyranid invasion", "The birth of Slaanesh" }, correct = 1 },
	{ q = "What is an STC (Standard Template Construct)?",
	  a = { "A type of plasma weapon fielded by the Adeptus Mechanicus", "An ancient AI database containing complete designs for Dark Age technology — finding a fragment can reshape the Imperium", "A Space Marine rank denoting mastery of siege warfare", "A Tau device that translates alien languages in real-time" }, correct = 1 },
	{ q = "What is the Void Dragon?",
	  a = { "A Tyranid bio-ship capable of eating moons", "A C'tan — possibly the most powerful shard, rumoured to be imprisoned beneath Mars and influencing the Mechanicus", "An Eldar god of the forge who taught them to shape Wraithbone", "A Chaos daemon bound within the Vengeful Spirit" }, correct = 1 },

	{ q = "What is the Grey Knights' unique trait?",
	  a = { "They are physically the largest Space Marines due to genhancement", "Every single Grey Knight is a potent psyker — they are the Imperium's dedicated anti-daemon Chapter", "They exclusively wield chainswords in close combat", "They are all psychic blanks immune to daemonic possession" }, correct = 1 },
	{ q = "Who is the Supreme Grand Master of the Grey Knights?",
	  a = { "Marneus Calgar", "Kaldor Draigo", "Dante", "Logan Grimnar" }, correct = 1 },
	{ q = "What is the Deathwatch?",
	  a = { "A Chaos warband", "The Chamber Militant of the Ordo Xenos — Space Marines seconded from many Chapters to hunt aliens", "An Imperial Guard regiment", "A Titan Legion" }, correct = 1 },
	{ q = "What makes Deathwatch Marines unique?",
	  a = { "They are all psykers", "Their silver left arm and shoulder pad — they return to their parent Chapter after service", "They are all veterans of the Horus Heresy", "They cannot speak" }, correct = 1 },

	{ q = "What is the 'Noosphere'?",
	  a = { "A physical library beneath the Imperial Palace", "The Mechanicus' wireless information realm — a machine-telepathic network where Tech-Priests share data directly", "A type of plasma weapon that leaves no radiation signature", "A gas giant in the Sol system used for fuel extraction" }, correct = 1 },
	{ q = "What is a Tech-Priest's ultimate goal?",
	  a = { "To purge all technology deemed heretical", "To replace weak flesh with blessed machine — pursuing the perfect union of man and machine", "To colonize uninhabited worlds in the Emperor's name", "To undergo the trials and become a full Space Marine" }, correct = 1 },
	{ q = "What is a Skitarius?",
	  a = { "A senior Tech-Priest who oversees a forge world's production", "A cybernetically augmented soldier of the Mechanicus — bionic limbs, programmed loyalty, and rad-weapons", "A type of Imperial Knight piloted by a bonded noble", "A Mechanicus cargo vessel hauling resources between forge worlds" }, correct = 1 },
	{ q = "What are the Collegia Titanica?",
	  a = { "A school for psykers", "The organization that operates the God-Machines — the Titans", "A branch of the Inquisition", "An Eldar institution" }, correct = 1 },
	{ q = "What is Mars to the Imperium?",
	  a = { "Just a forge world", "The home of the Adeptus Mechanicus and the second-most important planet after Terra", "A dead world", "A Necron tomb world" }, correct = 1 },
	{ q = "What is the 'Quest for Knowledge'?",
	  a = { "A Blood Angels ritual meditation before battle", "The core doctrine of the Cult Mechanicus — an eternal galaxy-wide hunt for lost archaeotech", "An Inquisition mandate to map every sector of the galaxy", "A Tau philosophical treatise on the Greater Good" }, correct = 1 },

	{ q = "What was the War in Heaven?",
	  a = { "The Emperor's unification of Terra during the Age of Strife", "An aeons-old galaxy-spanning conflict between the Old Ones, C'tan, and Necrontyr — the root of all later wars", "The seven-year siege of the Imperial Palace during the Horus Heresy", "The Imperium's crusade to reclaim worlds lost during the Age of Apostasy" }, correct = 1 },
	{ q = "What was the Siege of Terra?",
	  a = { "A minor skirmish", "The final battle of the Horus Heresy — Horus's forces assaulted the Imperial Palace", "An Ork invasion", "A Necron awakening" }, correct = 1 },
	{ q = "What happened at the Battle of Prospero?",
	  a = { "The Emperor defeated Horus", "The Space Wolves destroyed the Thousand Sons' homeworld — Magnus broke the Emperor's Webway project", "The Orks conquered an Imperial world", "The Tau joined the Imperium" }, correct = 1 },
	{ q = "What was the Drop Site Massacre at Isstvan V?",
	  a = { "A Tyranid attack", "Loyalist legions were ambushed by traitor legions — the true start of the Heresy's open warfare", "A Dark Eldar raid", "An Inquisition purge" }, correct = 1 },
	{ q = "What is the Devastation of Baal?",
	  a = { "A Chaos invasion of the Blood Angels' homeworld", "Hive Fleet Leviathan's assault on Baal — the Blood Angels almost wiped out", "A Necron attack", "An Ork WAAAGH!" }, correct = 1 },
		{ q = "What is the Pariah Nexus?",
		  a = { "A Chaos ritual site", "A region of space where Necrons are building anti-Warp pylons that suppress the Warp", "A Tau research station", "An Eldar Webway gate" }, correct = 1 },

		{ q = "Which Imperial body is infamous for endless records, tithes, and bureaucracy?", a = { "Adeptus Administratum", "Officio Assassinorum", "Adeptus Custodes", "Navis Nobilite" }, correct = 0 },
		{ q = "Which Imperial department supplies and organizes the Astra Militarum?", a = { "Adeptus Arbites", "Departmento Munitorum", "Adeptus Astra Telepathica", "Officio Medicae" }, correct = 1 },
		{ q = "Which Imperial institution trains many orphans for roles such as Commissars and Scions?", a = { "Navis Nobilite", "Collegia Titanica", "Schola Progenium", "Adeptus Astronomica" }, correct = 2 },
		{ q = "What is the Adeptus Ministorum better known as?", a = { "The Navigator Houses", "The Imperial Navy", "The Tech-Priesthood", "The Ecclesiarchy" }, correct = 3 },
		{ q = "Which organization operates the psychic beacon called the Astronomican?", a = { "Adeptus Astronomica", "Adeptus Arbites", "Adeptus Mechanicus", "Navis Nobilite" }, correct = 0 },
		{ q = "Which Imperial organization oversees sanctioned psykers and Black Ships?", a = { "Departmento Exacta", "Adeptus Astra Telepathica", "Estate Imperium", "Officio Assassinorum" }, correct = 1 },
		{ q = "What title is commonly given to the ruler of an Imperial world?", a = { "Lord Solar", "Princeps", "Planetary Governor", "Magos Dominus" }, correct = 2 },
		{ q = "What is the Imperial Tithe?", a = { "A Space Marine gene-seed ritual", "A Navigator family duel", "A Mechanicus data-prayer", "A levy of manpower, goods, or resources owed by Imperial worlds" }, correct = 3 },
		{ q = "Which legal code is enforced by the Adeptus Arbites?", a = { "Lex Imperialis", "Codex Astartes", "Treaty of Mars", "Book of Lorgar" }, correct = 0 },
		{ q = "What is a Rogue Trader's Warrant of Trade?", a = { "A hive-city arrest order", "A charter granting broad authority to explore and trade beyond Imperial borders", "A Mechanicus license for plasma weapons", "A Navy order for exterminatus" }, correct = 1 },
		{ q = "Which caste of mutant nobles guides Imperial ships through the Warp?", a = { "Astropaths", "Blanks", "Navigators", "Untouchables" }, correct = 2 },
		{ q = "What is an astropath mainly used for?", a = { "Repairing plasma reactors", "Piloting voidships", "Commanding Titans", "Sending psychic messages across interstellar distances" }, correct = 3 },
		{ q = "Which Imperial fleet handles most military void warfare?", a = { "Imperial Navy", "Merchant Fleet", "Black Ships", "Explorator Fleet" }, correct = 0 },
		{ q = "Which Imperial ships collect psykers from worlds across the Imperium?", a = { "Chartist Captains", "Black Ships", "Ark Mechanicus vessels", "Space Hulks" }, correct = 1 },
		{ q = "Which order of warriors is made up of psychic blanks and often fights beside Custodes?", a = { "Adepta Sororitas", "Deathwatch", "Sisters of Silence", "Eversor Temple" }, correct = 2 },
		{ q = "Which Imperial court or council rules Terra in the Emperor's name?", a = { "The Conclave of Har", "The Synod Ministra", "The Council of Nikaea", "The Senatorum Imperialis" }, correct = 3 },
		{ q = "Which Adepta Sororitas order type focuses on battlefield healing?", a = { "Orders Hospitaller", "Orders Dialogus", "Orders Famulous", "Orders Militant" }, correct = 0 },
		{ q = "Which Adepta Sororitas order type specializes in translation and sacred texts?", a = { "Orders Sabine", "Orders Dialogus", "Orders Pronatus", "Orders Vespila" }, correct = 1 },
		{ q = "Which Adepta Sororitas order type fights as the famous Sisters of Battle?", a = { "Orders Famulous", "Orders Hospitaller", "Orders Militant", "Orders Dialogus" }, correct = 2 },
		{ q = "What is a Canoness in the Adepta Sororitas?", a = { "A Navigator matriarch", "A Mechanicus data-saint", "A Guard artillery officer", "A senior commander of a Sororitas order" }, correct = 3 },
		{ q = "Which Sororitas unit uses jump packs and angelic imagery?", a = { "Seraphim", "Celestians", "Retributors", "Dominions" }, correct = 0 },
		{ q = "Which Sororitas heavy-support squad is known for massed heavy weapons?", a = { "Repentia", "Retributors", "Novitiates", "Hospitallers" }, correct = 1 },
		{ q = "Which Sororitas warriors seek redemption with eviscerators and little armour?", a = { "Dominions", "Seraphim", "Repentia", "Celestians" }, correct = 2 },
		{ q = "Which Sororitas vehicle is a pipe-organ missile tank?", a = { "Immolator", "Castigator", "Exorcist", "Repressor" }, correct = 3 },
		{ q = "Which Space Marine Chapter rules the realm of Ultramar?", a = { "Ultramarines", "Salamanders", "Raven Guard", "Iron Hands" }, correct = 0 },
		{ q = "Which Space Marine Chapter is strongly associated with speed, bikes, and Chogoris?", a = { "Imperial Fists", "White Scars", "Dark Angels", "Blood Ravens" }, correct = 1 },
		{ q = "Which Space Marine Chapter is known for fire, craftsmanship, and protecting civilians?", a = { "Raven Guard", "Iron Hands", "Salamanders", "Minotaurs" }, correct = 2 },
		{ q = "Which Space Marine Chapter is known for stealth, jump assaults, and Deliverance?", a = { "White Scars", "Ultramarines", "Salamanders", "Raven Guard" }, correct = 3 },
		{ q = "Which Space Marine Chapter reveres bionics and the phrase 'the flesh is weak'?", a = { "Iron Hands", "Space Wolves", "Blood Angels", "Crimson Fists" }, correct = 0 },
		{ q = "Which Chapter Master of the Ultramarines is famous for ruling Macragge?", a = { "Logan Grimnar", "Marneus Calgar", "Dante", "Kayvaan Shrike" }, correct = 1 },
		{ q = "Which Blood Angels Chapter Master is among the oldest living Space Marines?", a = { "Azrael", "Helbrecht", "Dante", "Tu'Shan" }, correct = 2 },
		{ q = "Which Dark Angels Supreme Grand Master leads the hunt for the Fallen?", a = { "Sicarius", "Pedro Kantor", "Tor Garadon", "Azrael" }, correct = 3 },
		{ q = "Which Black Templars leader bears the title High Marshal?", a = { "Helbrecht", "Dante", "Calgar", "Shrike" }, correct = 0 },
		{ q = "Which Crimson Fists Chapter Master is a famous survivor of Rynn's World?", a = { "Gabriel Seth", "Pedro Kantor", "Vulkan He'stan", "Asterion Moloc" }, correct = 1 },
		{ q = "Which Salamanders character searches for the lost artefacts of Vulkan?", a = { "Tu'Shan", "Adrax Agatone", "Vulkan He'stan", "Bray'arth Ashmantle" }, correct = 2 },
		{ q = "Which Raven Guard Chapter Master is known for lightning-claw strikes?", a = { "Kor'sarro Khan", "Cato Sicarius", "Uriel Ventris", "Kayvaan Shrike" }, correct = 3 },
		{ q = "Which Space Marine rank normally commands a company?", a = { "Captain", "Chaplain", "Techmarine", "Apothecary" }, correct = 0 },
		{ q = "Which Space Marine specialist preserves gene-seed and treats battle-brothers?", a = { "Librarian", "Apothecary", "Judiciar", "Ancient" }, correct = 1 },
		{ q = "Which Space Marine specialist maintains wargear and has ties to Mars?", a = { "Chaplain", "Librarian", "Techmarine", "Company Champion" }, correct = 2 },
		{ q = "Which Space Marine specialist serves as a battlefield priest and morale leader?", a = { "Apothecary", "Techmarine", "Ancient", "Chaplain" }, correct = 3 },
		{ q = "Which Space Marine specialist is a sanctioned psyker?", a = { "Librarian", "Judiciar", "Company Ancient", "Bladeguard Veteran" }, correct = 0 },
		{ q = "Which Space Marine warrior carries a Chapter or company banner?", a = { "Eliminator", "Ancient", "Eradicator", "Inceptor" }, correct = 1 },
		{ q = "Which Space Marine unit type is known for flamestorm gauntlets and heavy gravis armour?", a = { "Hellblasters", "Reivers", "Aggressors", "Suppressors" }, correct = 2 },
		{ q = "Which Space Marine unit specializes in plasma incinerators?", a = { "Infiltrators", "Intercessors", "Eradicators", "Hellblasters" }, correct = 3 },
		{ q = "Which Space Marine unit specializes in melta weapons for destroying armour?", a = { "Eradicators", "Eliminators", "Reivers", "Incursors" }, correct = 0 },
		{ q = "Which Primaris unit is known for jump-pack gravis assaults?", a = { "Desolators", "Inceptors", "Aggressors", "Bladeguard Veterans" }, correct = 1 },
		{ q = "Which Space Marine unit is associated with stealth sniping?", a = { "Assault Intercessors", "Inceptors", "Eliminators", "Terminators" }, correct = 2 },
		{ q = "Which Space Marine unit uses terror tactics, grapnel launchers, and skull masks?", a = { "Centurions", "Devastators", "Sternguard", "Reivers" }, correct = 3 },
		{ q = "Which First Founding Legion became the Ultramarines Chapter?", a = { "XIII Legion", "IV Legion", "VIII Legion", "XVII Legion" }, correct = 0 },
		{ q = "Which First Founding Legion became the White Scars Chapter?", a = { "VI Legion", "V Legion", "X Legion", "XIX Legion" }, correct = 1 },
		{ q = "Which First Founding Legion became the Salamanders Chapter?", a = { "VII Legion", "IX Legion", "XVIII Legion", "III Legion" }, correct = 2 },
		{ q = "Which First Founding Legion became the Raven Guard Chapter?", a = { "II Legion", "XI Legion", "XVI Legion", "XIX Legion" }, correct = 3 },
		{ q = "Which First Founding Legion became the Iron Hands Chapter?", a = { "X Legion", "XII Legion", "XV Legion", "XX Legion" }, correct = 0 },
		{ q = "Which Chapter's fortress-monastery is the asteroid stronghold called The Rock?", a = { "Imperial Fists", "Dark Angels", "Salamanders", "Raven Guard" }, correct = 1 },
		{ q = "Which Chapter's fortress-monastery is The Fang?", a = { "Blood Angels", "Black Templars", "Space Wolves", "Ultramarines" }, correct = 2 },
		{ q = "Which Chapter's mobile fortress-monastery is the Phalanx?", a = { "Raven Guard", "Iron Hands", "White Scars", "Imperial Fists" }, correct = 3 },
		{ q = "Which Space Marine Chapter recruits from Nocturne?", a = { "Salamanders", "Iron Hands", "Ultramarines", "Dark Angels" }, correct = 0 },
		{ q = "Which Space Marine Chapter recruits from Medusa?", a = { "White Scars", "Iron Hands", "Blood Angels", "Raven Guard" }, correct = 1 },
		{ q = "Which Space Marine Chapter recruits from Baal and its moons?", a = { "Imperial Fists", "Salamanders", "Blood Angels", "Dark Angels" }, correct = 2 },
		{ q = "Which Space Marine Chapter recruits from Fenris?", a = { "Ultramarines", "Iron Hands", "Black Templars", "Space Wolves" }, correct = 3 },
		{ q = "Which Space Marine Chapter is known for crusading fleets rather than a fixed Chapter world?", a = { "Black Templars", "Salamanders", "Raven Guard", "White Scars" }, correct = 0 },
		{ q = "Which Space Marine Chapter is famous for the Battle of Rynn's World?", a = { "Flesh Tearers", "Crimson Fists", "Carcharodons", "Exorcists" }, correct = 1 },
		{ q = "Which Blood Angels successor is known for extreme aggression and Gabriel Seth?", a = { "Lamenters", "Angels Encarmine", "Flesh Tearers", "Blood Drinkers" }, correct = 2 },
		{ q = "Which successor Chapter is famously unlucky and associated with a bleeding heart badge?", a = { "Black Dragons", "Mortifactors", "Red Scorpions", "Lamenters" }, correct = 3 },
		{ q = "Which Space Marine weapon fires mass-reactive explosive shells?", a = { "Boltgun", "Lasgun", "Shuriken catapult", "Pulse rifle" }, correct = 0 },
		{ q = "Which weapon type projects a disruption field around a blade?", a = { "Chain weapon", "Power weapon", "Needle weapon", "Grav weapon" }, correct = 1 },
		{ q = "Which Imperial weapon overheats because it contains sun-hot plasma?", a = { "Melta gun", "Flamer", "Plasma gun", "Autocannon" }, correct = 2 },
		{ q = "Which Imperial weapon is short-ranged and excels at burning through armour?", a = { "Sniper rifle", "Heavy stubber", "Grenade launcher", "Melta gun" }, correct = 3 },
		{ q = "Which Imperial weapon launches explosive shells in rapid fire?", a = { "Autocannon", "Lascannon", "Volkite charger", "Needle pistol" }, correct = 0 },
		{ q = "Which Imperial weapon fires coherent beams of intense light?", a = { "Storm bolter", "Lascannon", "Grav-cannon", "Conversion beamer" }, correct = 1 },
		{ q = "Which Imperial weapon bathes targets in burning promethium?", a = { "Plasma gun", "Melta gun", "Flamer", "Rail rifle" }, correct = 2 },
		{ q = "Which Imperial weapon uses gravity distortion to crush heavily armoured foes?", a = { "Volkite culverin", "Inferno pistol", "Needle rifle", "Grav-gun" }, correct = 3 },
		{ q = "Which tank is the iconic main battle tank of the Astra Militarum?", a = { "Leman Russ", "Rhino", "Predator", "Hammerhead" }, correct = 0 },
		{ q = "Which Imperial Guard vehicle is a common armoured personnel carrier?", a = { "Basilisk", "Chimera", "Baneblade", "Land Raider" }, correct = 1 },
		{ q = "Which Astra Militarum artillery vehicle mounts an Earthshaker cannon?", a = { "Wyvern", "Manticore", "Basilisk", "Hydra" }, correct = 2 },
		{ q = "Which Astra Militarum super-heavy tank is among the most famous in the Imperium?", a = { "Chimera", "Taurox", "Sentinel", "Baneblade" }, correct = 3 },
		{ q = "Which Astra Militarum walker is used for scouting and support?", a = { "Sentinel", "Dreadknight", "Killa Kan", "Wraithlord" }, correct = 0 },
		{ q = "Which elite Astra Militarum troops are trained for high-risk missions and drop assaults?", a = { "Cadians", "Tempestus Scions", "Ratlings", "Rough Riders" }, correct = 1 },
		{ q = "Which abhuman snipers are small, stealthy, and excellent marksmen?", a = { "Ogryns", "Beastmen", "Ratlings", "Squats" }, correct = 2 },
		{ q = "Which Astra Militarum regiment is famous for gas masks and siege warfare?", a = { "Catachan Jungle Fighters", "Mordian Iron Guard", "Tallarn Desert Raiders", "Death Korps of Krieg" }, correct = 3 },
		{ q = "Which Astra Militarum regiment is famous for jungle warfare?", a = { "Catachan Jungle Fighters", "Vostroyan Firstborn", "Mordian Iron Guard", "Valhallan Ice Warriors" }, correct = 0 },
		{ q = "Which Astra Militarum regiment is famous for desert warfare and fast raids?", a = { "Cadians", "Tallarn Desert Raiders", "Steel Legion", "Praetorian Guard" }, correct = 1 },
		{ q = "Which Astra Militarum regiment is known for disciplined parade-ground precision?", a = { "Valhallans", "Catachans", "Mordian Iron Guard", "Savlar Chem-Dogs" }, correct = 2 },
		{ q = "Which Astra Militarum regiment is associated with Armageddon and mechanized warfare?", a = { "Tanith First-and-Only", "Elysian Drop Troops", "Harakoni Warhawks", "Armageddon Steel Legion" }, correct = 3 },
		{ q = "Which world is the home of the Adeptus Mechanicus?", a = { "Mars", "Baal", "Nocturne", "Armageddon" }, correct = 0 },
		{ q = "Which Mechanicus rank is a senior Tech-Priest master of machines?", a = { "Princeps", "Magos", "Canoness", "Phaeron" }, correct = 1 },
		{ q = "Which Mechanicus troops are cybernetic infantry of the Skitarii legions?", a = { "Sisters Repentia", "Tempestus Scions", "Skitarii Rangers", "Kabalite Warriors" }, correct = 2 },
		{ q = "Which Mechanicus warriors are heavily augmented battle-servitors with tracked bodies?", a = { "Secutarii", "Electro-Priests", "Sicarian Ruststalkers", "Kataphron Servitors" }, correct = 3 },
		{ q = "Which Mechanicus cultists weaponize bio-electric faith?", a = { "Electro-Priests", "Ruststalkers", "Pteraxii", "Serberys Raiders" }, correct = 0 },
		{ q = "Which Mechanicus assassins are known for transonic blades?", a = { "Corpuscarii", "Sicarian Ruststalkers", "Vanguard", "Ironstriders" }, correct = 1 },
		{ q = "Which Mechanicus walkers are long-legged cavalry engines?", a = { "Onager Dunecrawlers", "Skorpius Disintegrators", "Ironstrider Ballistarii", "Archaeopters" }, correct = 2 },
		{ q = "Which Mechanicus vehicle resembles a crab-like weapons platform?", a = { "Rhino", "Basilisk", "Falcon", "Onager Dunecrawler" }, correct = 3 },
		{ q = "Which Titan class is smaller than a Warlord but still a major god-machine?", a = { "Reaver Titan", "Knight Armiger", "Sentinel", "Dreadnought" }, correct = 0 },
		{ q = "Which Titan class is among the largest commonly fielded Imperial Titans?", a = { "Warhound Titan", "Warlord Titan", "Questoris Knight", "Baneblade" }, correct = 1 },
		{ q = "Which Titan class is a fast scout god-machine?", a = { "Warmaster Titan", "Reaver Titan", "Warhound Titan", "Castigator Knight" }, correct = 2 },
		{ q = "What title is given to a Titan's commander?", a = { "Canoness", "Commissar", "Shas'o", "Princeps" }, correct = 3 },
		{ q = "Which nobles pilot towering Knight suits for the Imperium?", a = { "Knight House scions", "Navigator savants", "Astra Telepathica adepts", "Administratum scribes" }, correct = 0 },
		{ q = "Which class of Imperial Knight is a common large battle suit?", a = { "Armiger", "Questoris", "Sentinel", "Dunecrawler" }, correct = 1 },
		{ q = "Which smaller Knight class often supports larger Knight suits?", a = { "Cerastus", "Dominus", "Armiger", "Acastus" }, correct = 2 },
		{ q = "Which fallen Knight pilots swear themselves to Chaos?", a = { "Questor Imperialis", "Collegia Titanica", "Secutarii", "Chaos Knights" }, correct = 3 },
		{ q = "Which Aeldari path produces the warrior cults called Aspect Warriors?", a = { "Path of the Warrior", "Path of the Seer", "Path of the Outcast", "Path of Command" }, correct = 0 },
		{ q = "Which Aeldari Aspect Warriors wear heavy armour and carry fusion guns?", a = { "Howling Banshees", "Fire Dragons", "Swooping Hawks", "Warp Spiders" }, correct = 1 },
		{ q = "Which Aeldari Aspect Warriors are screaming melee specialists?", a = { "Dire Avengers", "Dark Reapers", "Howling Banshees", "Striking Scorpions" }, correct = 2 },
		{ q = "Which Aeldari Aspect Warriors are stealthy close-combat hunters?", a = { "Fire Dragons", "Dire Avengers", "Swooping Hawks", "Striking Scorpions" }, correct = 3 },
		{ q = "Which Aeldari Aspect Warriors are disciplined shuriken infantry?", a = { "Dire Avengers", "Warp Spiders", "Dark Reapers", "Shining Spears" }, correct = 0 },
		{ q = "Which Aeldari Aspect Warriors use jump generators to flicker through the Warp?", a = { "Swooping Hawks", "Warp Spiders", "Fire Dragons", "Howling Banshees" }, correct = 1 },
		{ q = "Which Aeldari Aspect Warriors specialize in long-range missile fire?", a = { "Shining Spears", "Dire Avengers", "Dark Reapers", "Striking Scorpions" }, correct = 2 },
		{ q = "Which Aeldari Aspect Warriors are winged aerial fighters?", a = { "Dark Reapers", "Fire Dragons", "Warp Spiders", "Swooping Hawks" }, correct = 3 },
		{ q = "Which Aeldari warriors ride jetbikes and fight as lance cavalry?", a = { "Shining Spears", "Howling Banshees", "Dark Reapers", "Dire Avengers" }, correct = 0 },
		{ q = "Which Aeldari psyker reads fate and guides a craftworld?", a = { "Warlock", "Farseer", "Spiritseer", "Shadowseer" }, correct = 1 },
		{ q = "Which Aeldari psyker communes with the souls of the dead?", a = { "Autarch", "Farseer", "Spiritseer", "Exarch" }, correct = 2 },
		{ q = "Which Aeldari commander has walked many warrior paths?", a = { "Warlock", "Bonesinger", "Phoenix Lord", "Autarch" }, correct = 3 },
		{ q = "Which Aeldari constructs contain the souls of dead warriors?", a = { "Wraithguard", "Kabalites", "Krootox", "Immortals" }, correct = 0 },
		{ q = "Which Aeldari towering wraith construct is larger than Wraithguard?", a = { "Vyper", "Wraithlord", "Falcon", "War Walker" }, correct = 1 },
		{ q = "Which Aeldari super-heavy wraith construct is a towering ghost warrior?", a = { "Wraithlord", "Avatar", "Wraithknight", "Fire Prism" }, correct = 2 },
		{ q = "Which molten war-god fragment can manifest in a craftworld's hour of need?", a = { "Yncarne", "Cegorach", "Isha", "Avatar of Khaine" }, correct = 3 },
		{ q = "Which Aeldari material responds to psychic shaping and song?", a = { "Wraithbone", "Necrodermis", "Ceramite", "Adamantium" }, correct = 0 },
		{ q = "Which craftworld is strongly associated with prophecy and Farseers?", a = { "Biel-Tan", "Ulthwe", "Saim-Hann", "Iyanden" }, correct = 1 },
		{ q = "Which craftworld is known for wild jetbike clans?", a = { "Alaitoc", "Ulthwe", "Saim-Hann", "Iyanden" }, correct = 2 },
		{ q = "Which craftworld is known for many ghost warriors after disaster?", a = { "Biel-Tan", "Saim-Hann", "Alaitoc", "Iyanden" }, correct = 3 },
		{ q = "Which craftworld is known for strict Rangers and the Path of the Outcast?", a = { "Alaitoc", "Iyanden", "Ulthwe", "Biel-Tan" }, correct = 0 },
		{ q = "Which craftworld is strongly associated with militant Aspect Warrior hosts?", a = { "Saim-Hann", "Biel-Tan", "Ulthwe", "Iyanden" }, correct = 1 },
		{ q = "Which Aeldari god is the Laughing God of the Harlequins?", a = { "Khaine", "Isha", "Cegorach", "Asuryan" }, correct = 2 },
		{ q = "Which Harlequin role is a psyker and master of illusion?", a = { "Death Jester", "Solitaire", "Troupe Master", "Shadowseer" }, correct = 3 },
		{ q = "Which Harlequin performer wields heavy weapons and morbid theatrics?", a = { "Death Jester", "Shadowseer", "Warlock", "Autarch" }, correct = 0 },
		{ q = "Which Harlequin role represents Slaanesh in sacred performances?", a = { "Troupe Master", "Solitaire", "Great Harlequin", "Skyweaver" }, correct = 1 },
		{ q = "Which Aeldari faction worships Ynnead, the god of the dead?", a = { "Corsairs", "Harlequins", "Ynnari", "Exodites" }, correct = 2 },
		{ q = "Which being is the avatar of Ynnead?", a = { "Avatar of Khaine", "The Nightbringer", "The Deceiver", "The Yncarne" }, correct = 3 },
		{ q = "Which Aeldari are often raiders and freebooters between craftworlds and Commorragh?", a = { "Corsairs", "Neophytes", "Kroot", "Pathfinders" }, correct = 0 },
		{ q = "Which Aeldari live on maiden worlds and often ride great reptiles?", a = { "Ynnari", "Exodites", "Incubi", "Voidscarred" }, correct = 1 },
		{ q = "Which Drukhari social group dominates Commorragh through raids and politics?", a = { "Wych Cults", "Haemonculus Covens", "Kabals", "Aspect Shrines" }, correct = 2 },
		{ q = "Which Drukhari group stages gladiatorial arena combat?", a = { "Kabals", "Covens", "Incubi Shrines", "Wych Cults" }, correct = 3 },
		{ q = "Which Drukhari group creates grotesque fleshcraft and resurrection arts?", a = { "Haemonculus Covens", "Wych Cults", "Ranger Bands", "Seer Councils" }, correct = 0 },
		{ q = "Which Drukhari leader commands a Kabal?", a = { "Succubus", "Archon", "Haemonculus", "Autarch" }, correct = 1 },
		{ q = "Which Drukhari leader commands a Wych Cult?", a = { "Archon", "Farseer", "Succubus", "Shadowseer" }, correct = 2 },
		{ q = "Which Drukhari transport skimmer is a common raiding craft?", a = { "Wave Serpent", "Falcon", "Venom", "Raider" }, correct = 3 },
		{ q = "Which Drukhari venom weaponry fires crystalline toxins?", a = { "Splinter weapons", "Shuriken weapons", "Gauss weapons", "Pulse weapons" }, correct = 0 },
		{ q = "Which Drukhari beast is a bat-winged predator used in arenas and raids?", a = { "Clawed Fiend", "Razorwing Flock", "Khymera", "Ur-Ghul" }, correct = 1 },
		{ q = "Which Drukhari construct is a stitched monster made by Haemonculi?", a = { "Incubus", "Mandrake", "Grotesque", "Wrack" }, correct = 2 },
		{ q = "Which shadowy Drukhari killers are linked to Aelindrach?", a = { "Kabalites", "Wyches", "Scourges", "Mandrakes" }, correct = 3 },
		{ q = "Which Ork Oddboy channels dangerous psychic Waaagh energy?", a = { "Weirdboy", "Painboy", "Runtherd", "Big Mek" }, correct = 0 },
		{ q = "Which Ork Oddboy performs crude surgery and bionic work?", a = { "Weirdboy", "Painboy", "Mekboy", "Runtherd" }, correct = 1 },
		{ q = "Which Ork Oddboy herds Gretchin and squigs?", a = { "Painboy", "Big Mek", "Runtherd", "Weirdboy" }, correct = 2 },
		{ q = "Which Ork specialist builds kustom force fields and huge machines?", a = { "Painboy", "Weirdboy", "Runtherd", "Big Mek" }, correct = 3 },
		{ q = "Which smaller greenskins serve Orks as cowardly helpers?", a = { "Gretchin", "Kroot", "Vespid", "Ratlings" }, correct = 0 },
		{ q = "Which Ork creatures range from pets to living weapons and food?", a = { "Rippers", "Squigs", "Nurglings", "Scarabs" }, correct = 1 },
		{ q = "Which Ork clan is associated with speed and red vehicles?", a = { "Goffs", "Deathskulls", "Evil Sunz", "Blood Axes" }, correct = 2 },
		{ q = "Which Ork clan is famous for brutal melee and black-and-white checks?", a = { "Snakebites", "Bad Moons", "Deathskulls", "Goffs" }, correct = 3 },
		{ q = "Which Ork clan is known for wealth, flashy gear, and big teef?", a = { "Bad Moons", "Evil Sunz", "Blood Axes", "Goffs" }, correct = 0 },
		{ q = "Which Ork clan is known for looting and lucky blue paint?", a = { "Snakebites", "Deathskulls", "Freebooterz", "Evil Sunz" }, correct = 1 },
		{ q = "Which Ork clan is considered unusually disciplined and fond of camouflage?", a = { "Goffs", "Bad Moons", "Blood Axes", "Snakebites" }, correct = 2 },
		{ q = "Which Ork clan clings to old ways, squigs, and tough living?", a = { "Bad Moons", "Evil Sunz", "Deathskulls", "Snakebites" }, correct = 3 },
		{ q = "Which Ork freebooters live as pirates and mercenaries?", a = { "Freebooterz", "Boyz", "Nobz", "Stormboyz" }, correct = 0 },
		{ q = "Which Ork infantry are the basic fighting mobs?", a = { "Nobz", "Boyz", "Meganobz", "Kommandos" }, correct = 1 },
		{ q = "Which Orks are bigger veterans above normal Boyz?", a = { "Gretchin", "Runts", "Nobz", "Snotlings" }, correct = 2 },
		{ q = "Which Ork unit wears heavy powered armour?", a = { "Stormboyz", "Flash Gitz", "Kommandos", "Meganobz" }, correct = 3 },
		{ q = "Which Ork vehicle is a ramshackle transport truck?", a = { "Trukk", "Battlewagon", "Dakkajet", "Deff Dread" }, correct = 0 },
		{ q = "Which Ork walker is a large stompy war machine crewed by an Ork?", a = { "Killa Kan", "Deff Dread", "Sentinel", "Wraithlord" }, correct = 1 },
		{ q = "Which small Ork walker is often crewed by a Grot?", a = { "Deff Dread", "Morkanaut", "Killa Kan", "Gorkanaut" }, correct = 2 },
		{ q = "Which gigantic Ork effigy-machine is a titan-scale idol of war?", a = { "Battlewagon", "Dakkajet", "Deffkopta", "Stompa" }, correct = 3 },
		{ q = "Which Necron rank is a powerful ruler of a dynasty?", a = { "Phaeron", "Ethicarch", "Warboss", "Archon" }, correct = 0 },
		{ q = "Which Necron leader commonly commands tomb armies beneath a Phaeron?", a = { "Cryptek", "Overlord", "Immortal", "Deathmark" }, correct = 1 },
		{ q = "Which Necron techno-sorcerers manipulate arcane science?", a = { "Lychguard", "Flayed Ones", "Crypteks", "Praetorians" }, correct = 2 },
		{ q = "Which Necron infantry are the most common basic soldiers?", a = { "Immortals", "Deathmarks", "Lychguard", "Warriors" }, correct = 3 },
		{ q = "Which Necron infantry are elite warriors with heavier bodies and weapons?", a = { "Immortals", "Canoptek Scarabs", "Warriors", "Flayed Ones" }, correct = 0 },
		{ q = "Which Necron assassins phase in to mark and kill chosen targets?", a = { "Lychguard", "Deathmarks", "Triarch Praetorians", "Tomb Blades" }, correct = 1 },
		{ q = "Which Necron bodyguards protect nobles with shields and warscythes?", a = { "Immortals", "Deathmarks", "Lychguard", "Warriors" }, correct = 2 },
		{ q = "Which Necron agents once enforced ancient dynastic law across the stars?", a = { "Flayed Ones", "Canoptek Wraiths", "Skorpekh Destroyers", "Triarch Praetorians" }, correct = 3 },
		{ q = "Which Necron curse makes victims wear the skins of the living?", a = { "Flayer Curse", "Destroyer Curse", "Rubric Curse", "Pariah Curse" }, correct = 0 },
		{ q = "Which Necron cult seeks to destroy all organic life in obsessive hatred?", a = { "Triarch Guard", "Destroyer Cult", "Canoptek Court", "Chronomancer Circle" }, correct = 1 },
		{ q = "Which Necron constructs are insect-like tomb maintenance machines?", a = { "Immortals", "Lychguard", "Canoptek Scarabs", "Deathmarks" }, correct = 2 },
		{ q = "Which Necron constructs phase through matter and attack with whip coils?", a = { "Tomb Blades", "Skorpekh Destroyers", "Cryptothralls", "Canoptek Wraiths" }, correct = 3 },
		{ q = "Which Necron dynasty is strongly associated with Szarekh's return?", a = { "Szarekhan Dynasty", "Sautekh Dynasty", "Mephrit Dynasty", "Novokh Dynasty" }, correct = 0 },
		{ q = "Which Necron dynasty is famous for Imotekh the Stormlord?", a = { "Nihilakh Dynasty", "Sautekh Dynasty", "Szarekhan Dynasty", "Nephrekh Dynasty" }, correct = 1 },
		{ q = "Which Necron dynasty is associated with Trazyn's museum world Solemnace?", a = { "Novokh Dynasty", "Mephrit Dynasty", "Nihilakh Dynasty", "Sautekh Dynasty" }, correct = 2 },
		{ q = "Which Necron weapon type strips targets atom by atom?", a = { "Tesla weapons", "Synaptic weapons", "Shuriken weapons", "Gauss weapons" }, correct = 3 },
		{ q = "Which Necron weapon type arcs lightning between targets?", a = { "Tesla weapons", "Gauss weapons", "Melta weapons", "Volkite weapons" }, correct = 0 },
		{ q = "Which C'tan shard embodies death and is called the Nightbringer?", a = { "The Deceiver", "Aza'gorod", "Nyadra'zatha", "Mephet'ran" }, correct = 1 },
		{ q = "Which C'tan shard is famous for trickery and manipulation?", a = { "The Void Dragon", "The Nightbringer", "The Deceiver", "The Burning One" }, correct = 2 },
		{ q = "Which ancient race became the Necrons through biotransference?", a = { "Old Ones", "Aeldari", "C'tan", "Necrontyr" }, correct = 3 },
		{ q = "What was biotransference?", a = { "The transfer of Necrontyr minds into living metal bodies", "A Tau caste ceremony", "An Ork spore cycle", "A Tyranid digestion process" }, correct = 0 },
		{ q = "Which Necron engines create anti-Warp null zones in many recent stories?", a = { "Doomsday Arks", "Blackstone pylons", "Monolith gates", "Tesseract labyrinths" }, correct = 1 },
		{ q = "Which Necron device is a small prison for powerful beings such as C'tan shards?", a = { "Ghost Ark", "Resurrection Orb", "Tesseract Labyrinth", "Chronometron" }, correct = 2 },
		{ q = "Which Necron vehicle repairs and transports Warrior phalanxes?", a = { "Doom Scythe", "Annihilation Barge", "Command Barge", "Ghost Ark" }, correct = 3 },
		{ q = "Which Tyranid creatures provide synapse control over lesser organisms?", a = { "Tyranid Warriors", "Ripper Swarms", "Gargoyles", "Biovores" }, correct = 0 },
		{ q = "Which Tyranid monster is a towering synapse commander with a lash whip or guns?", a = { "Carnifex", "Hive Tyrant", "Trygon", "Haruspex" }, correct = 1 },
		{ q = "Which winged Tyranid swarm creatures serve as flying infantry?", a = { "Hormagaunts", "Termagants", "Gargoyles", "Genestealers" }, correct = 2 },
		{ q = "Which Tyranid gaunts are fast melee leapers?", a = { "Termagants", "Gargoyles", "Rippers", "Hormagaunts" }, correct = 3 },
		{ q = "Which Tyranid gaunts usually carry fleshborers?", a = { "Termagants", "Hormagaunts", "Gargoyles", "Raveners" }, correct = 0 },
		{ q = "Which Tyranid organisms are tiny biomass-consuming swarms?", a = { "Lictors", "Rippers", "Zoanthropes", "Pyrovores" }, correct = 1 },
		{ q = "Which Tyranid infiltrators are famous for claws, speed, and cult infection?", a = { "Termagants", "Rippers", "Genestealers", "Tyrant Guard" }, correct = 2 },
		{ q = "Which Tyranid assassin-beast stalks prey ahead of the swarm?", a = { "Carnifex", "Exocrine", "Harpy", "Lictor" }, correct = 3 },
		{ q = "Which Tyranid organism is a living battering ram and heavy assault beast?", a = { "Carnifex", "Biovore", "Venomthrope", "Neurogaunt" }, correct = 0 },
		{ q = "Which Tyranid artillery organism launches spore mines?", a = { "Exocrine", "Biovore", "Toxicrene", "Trygon" }, correct = 1 },
		{ q = "Which Tyranid gun-beast fires a massive bio-plasmic cannon?", a = { "Haruspex", "Maleceptor", "Exocrine", "Mawloc" }, correct = 2 },
		{ q = "Which Tyranid tunneling monster erupts from below with a serpentine body?", a = { "Tervigon", "Carnifex", "Hive Guard", "Trygon" }, correct = 3 },
		{ q = "Which Tyranid tunneler bursts up to swallow prey from beneath?", a = { "Mawloc", "Trygon", "Tyrannofex", "Harpy" }, correct = 0 },
		{ q = "Which Tyranid creature births broods of Termagants?", a = { "Maleceptor", "Tervigon", "Haruspex", "Lictor" }, correct = 1 },
		{ q = "Which Tyranid guard-beasts protect Hive Tyrants?", a = { "Tyranid Warriors", "Raveners", "Tyrant Guard", "Gargoyles" }, correct = 2 },
		{ q = "Which Tyranid organisms form a psychic choir around Zoanthropes?", a = { "Venomthropes", "Neurogaunts", "Ripper Swarms", "Neurothropes" }, correct = 3 },
		{ q = "Which Genestealer Cult leader is the first purestrain patriarch of a cult?", a = { "Patriarch", "Magus", "Primus", "Clamavus" }, correct = 0 },
		{ q = "Which Genestealer Cult psyker guides the cult's faith and visions?", a = { "Primus", "Magus", "Kelermorph", "Nexos" }, correct = 1 },
		{ q = "Which Genestealer Cult commander is a military leader of the uprising?", a = { "Patriarch", "Biophagus", "Primus", "Sanctus" }, correct = 2 },
		{ q = "Which Genestealer Cult gunslinger is a folk-hero assassin?", a = { "Clamavus", "Nexos", "Locus", "Kelermorph" }, correct = 3 },
		{ q = "Which Genestealer Cult agent spreads propaganda and signals revolt?", a = { "Clamavus", "Biophagus", "Abominant", "Reductus Saboteur" }, correct = 0 },
		{ q = "Which Genestealer Cult specialist studies mutation and biology?", a = { "Locus", "Biophagus", "Primus", "Acolyte Iconward" }, correct = 1 },
		{ q = "Which heavily mutated Genestealer Cult brute often leads Aberrants?", a = { "Nexos", "Sanctus", "Abominant", "Magus" }, correct = 2 },
		{ q = "Which Genestealer Cult icon bearer inspires nearby hybrids?", a = { "Primus", "Kelermorph", "Patriarch", "Acolyte Iconward" }, correct = 3 },
		{ q = "Which Tau caste forms the Empire's warriors?", a = { "Fire Caste", "Earth Caste", "Water Caste", "Air Caste" }, correct = 0 },
		{ q = "Which Tau caste builds machines, weapons, and infrastructure?", a = { "Water Caste", "Earth Caste", "Fire Caste", "Ethereal Caste" }, correct = 1 },
		{ q = "Which Tau caste handles diplomacy and trade?", a = { "Air Caste", "Earth Caste", "Water Caste", "Fire Caste" }, correct = 2 },
		{ q = "Which Tau caste pilots starships and aircraft?", a = { "Fire Caste", "Ethereal Caste", "Water Caste", "Air Caste" }, correct = 3 },
		{ q = "Which Tau caste provides spiritual and political leadership?", a = { "Ethereal Caste", "Earth Caste", "Air Caste", "Fire Caste" }, correct = 0 },
		{ q = "What is the Tau name for a Fire Warrior?", a = { "Kor'la", "Shas'la", "Por'ui", "Fio'o" }, correct = 1 },
		{ q = "What is the Tau name for an Ethereal?", a = { "Shas'o", "Kor'el", "Aun", "Por'vre" }, correct = 2 },
		{ q = "Which Tau commander leads the Farsight Enclaves?", a = { "Commander Shadowsun", "Aun'Va", "Longstrike", "Commander Farsight" }, correct = 3 },
		{ q = "Which Tau commander is famous for stealth and Kauyon tactics?", a = { "Commander Shadowsun", "Commander Farsight", "Aun'Shi", "Darkstrider" }, correct = 0 },
		{ q = "Which Tau doctrine emphasizes patient ambush and the killing blow?", a = { "Mont'ka", "Kauyon", "Malk'la", "Or'es" }, correct = 1 },
		{ q = "Which Tau doctrine emphasizes the sudden killing strike?", a = { "Kauyon", "Por'hui", "Mont'ka", "Fio'tak" }, correct = 2 },
		{ q = "Which Tau battlesuit is the common crisis-class combat suit?", a = { "XV88 Broadside", "KV128 Stormsurge", "XV95 Ghostkeel", "XV8 Crisis" }, correct = 3 },
		{ q = "Which Tau battlesuit is known for heavy railgun or missile support?", a = { "XV88 Broadside", "XV25 Stealth", "XV8 Crisis", "XV104 Riptide" }, correct = 0 },
		{ q = "Which Tau battlesuit is a large heavy assault suit with a nova reactor?", a = { "XV8 Crisis", "XV104 Riptide", "XV15 Stealth", "XV86 Coldstar" }, correct = 1 },
		{ q = "Which Tau battlesuit is a stealth infiltration suit larger than Stealth Teams?", a = { "Broadside", "Stormsurge", "Ghostkeel", "Crisis" }, correct = 2 },
		{ q = "Which Tau war machine is a huge ballistic suit, not a true battlesuit?", a = { "Riptide", "Broadside", "Ghostkeel", "Stormsurge" }, correct = 3 },
		{ q = "Which Tau weapon is their iconic infantry energy rifle?", a = { "Pulse rifle", "Lasgun", "Gauss flayer", "Splinter rifle" }, correct = 0 },
		{ q = "Which Tau weapon is famous for extreme armour penetration on Hammerheads?", a = { "Ion cannon", "Railgun", "Burst cannon", "Fusion blaster" }, correct = 1 },
		{ q = "Which Tau alien auxiliaries are winged insectoid fighters?", a = { "Kroot", "Demiurg", "Vespid", "Gue'vesa" }, correct = 2 },
		{ q = "Which humans serve the Tau Empire as auxiliaries?", a = { "Squats", "Navigators", "Abhumans", "Gue'vesa" }, correct = 3 },
		{ q = "Which Leagues of Votann people are also called Kin?", a = { "Kin", "Kroot", "Kinebrach", "Krork" }, correct = 0 },
		{ q = "Which ancient machine intelligences guide the Leagues of Votann?", a = { "Spirit Stones", "Ancestor Cores", "Noospheres", "Blackstone Engines" }, correct = 1 },
		{ q = "Which cloned Kin lines define common traits and roles?", a = { "Septs", "Kabals", "Cloneskeins", "Regiments" }, correct = 2 },
		{ q = "Which Leagues of Votann warriors are basic armoured infantry?", a = { "Cthonian Beserks", "Hernkyn Pioneers", "Einhyr Hearthguard", "Hearthkyn Warriors" }, correct = 3 },
		{ q = "Which Kin are void-suited scouts and outriders?", a = { "Hernkyn", "Einhyr", "Grimnyr", "Brokhyr" }, correct = 0 },
		{ q = "Which Kin are elite exo-armoured warriors?", a = { "Hearthkyn", "Einhyr", "Hernkyn", "Sagitaur" }, correct = 1 },
		{ q = "Which Kin are engineers and forge-masters?", a = { "Grimnyr", "Hearthkyn", "Brokhyr", "Cthonian" }, correct = 2 },
		{ q = "Which Kin are psyker-like barrier-tech mystics?", a = { "Einhyr", "Hernkyn", "Brokhyr", "Grimnyr" }, correct = 3 },
		{ q = "Which Chaos Space Marine Legion is known for terror tactics and flayed trophies?", a = { "Night Lords", "Iron Warriors", "Alpha Legion", "Word Bearers" }, correct = 0 },
		{ q = "Which Chaos Space Marine Legion is known for secrecy and the hydra symbol?", a = { "Night Lords", "Alpha Legion", "World Eaters", "Death Guard" }, correct = 1 },
		{ q = "Which Chaos Space Marine Legion is known for dark scripture and daemon worship?", a = { "Iron Warriors", "Emperor's Children", "Word Bearers", "Night Lords" }, correct = 2 },
		{ q = "Which Chaos Space Marine Legion is known for siegecraft and bitter rivalry with the Imperial Fists?", a = { "Black Legion", "Alpha Legion", "Thousand Sons", "Iron Warriors" }, correct = 3 },
		{ q = "Which Chaos Space Marine Legion was once led by Konrad Curze?", a = { "Night Lords", "Word Bearers", "Death Guard", "Iron Warriors" }, correct = 0 },
		{ q = "Which Chaos Space Marine Legion was led by Lorgar?", a = { "Alpha Legion", "Word Bearers", "World Eaters", "Emperor's Children" }, correct = 1 },
		{ q = "Which Chaos Space Marine Legion was led by Perturabo?", a = { "Night Lords", "Alpha Legion", "Iron Warriors", "Death Guard" }, correct = 2 },
		{ q = "Which Chaos Space Marine Legion was led by Alpharius and Omegon?", a = { "Word Bearers", "World Eaters", "Thousand Sons", "Alpha Legion" }, correct = 3 },
		{ q = "Which Chaos Space Marine rank is a priest of the Dark Gods?", a = { "Dark Apostle", "Warpsmith", "Exalted Champion", "Master of Executions" }, correct = 0 },
		{ q = "Which Chaos Space Marine specialist corrupts and maintains daemon engines?", a = { "Dark Apostle", "Warpsmith", "Noise Marine", "Possessed" }, correct = 1 },
		{ q = "Which Chaos Marines are fused with daemons in their bodies?", a = { "Havocs", "Raptors", "Possessed", "Chosen" }, correct = 2 },
		{ q = "Which Chaos Space Marine infantry are veteran elites favored by champions?", a = { "Cultists", "Traitor Guardsmen", "Havocs", "Chosen" }, correct = 3 },
		{ q = "Which Chaos Space Marine heavy weapon squads are called Havocs?", a = { "Havocs", "Raptors", "Warp Talons", "Legionaries" }, correct = 0 },
		{ q = "Which Chaos jump troops are terror assault Marines?", a = { "Chosen", "Raptors", "Noise Marines", "Rubric Marines" }, correct = 1 },
		{ q = "Which Chaos jump troops are daemonic clawed hunters?", a = { "Raptors", "Havocs", "Warp Talons", "Cultists" }, correct = 2 },
		{ q = "Which daemon engine is a spider-like artillery walker?", a = { "Heldrake", "Maulerfiend", "Venomcrawler", "Defiler" }, correct = 3 },
		{ q = "Which daemon engine is a draconic flying machine?", a = { "Heldrake", "Forgefiend", "Defiler", "Lord of Skulls" }, correct = 0 },
		{ q = "Which daemon engine is built for ranged firepower?", a = { "Maulerfiend", "Forgefiend", "Heldrake", "Helbrute" }, correct = 1 },
		{ q = "Which daemon engine is built for melee siege attacks?", a = { "Forgefiend", "Defiler", "Maulerfiend", "Venomcrawler" }, correct = 2 },
		{ q = "Which Chaos walker often contains a tormented Chaos Marine?", a = { "Defiler", "Heldrake", "Forgefiend", "Helbrute" }, correct = 3 },
		{ q = "Which Khorne daemons are basic horned foot soldiers?", a = { "Bloodletters", "Plaguebearers", "Daemonettes", "Pink Horrors" }, correct = 0 },
		{ q = "Which Nurgle daemons are one-eyed tallying foot soldiers?", a = { "Bloodletters", "Plaguebearers", "Daemonettes", "Screamers" }, correct = 1 },
		{ q = "Which Slaanesh daemons are swift clawed foot soldiers?", a = { "Nurglings", "Pink Horrors", "Daemonettes", "Bloodletters" }, correct = 2 },
		{ q = "Which Tzeentch daemons split and multiply in lesser forms?", a = { "Plaguebearers", "Daemonettes", "Bloodletters", "Horrors" }, correct = 3 },
		{ q = "Which greater daemon serves Khorne?", a = { "Bloodthirster", "Great Unclean One", "Lord of Change", "Keeper of Secrets" }, correct = 0 },
		{ q = "Which greater daemon serves Nurgle?", a = { "Bloodthirster", "Great Unclean One", "Keeper of Secrets", "Avatar of Khaine" }, correct = 1 },
		{ q = "Which greater daemon serves Tzeentch?", a = { "Keeper of Secrets", "Bloodthirster", "Lord of Change", "Great Unclean One" }, correct = 2 },
		{ q = "Which greater daemon serves Slaanesh?", a = { "Lord of Change", "Great Unclean One", "Bloodthirster", "Keeper of Secrets" }, correct = 3 },
		{ q = "Which Death Guard champion is called the Lord of Contagion in many plague hosts?", a = { "Lord of Contagion", "Dark Apostle", "Master of Possession", "Exalted Sorcerer" }, correct = 0 },
		{ q = "Which Thousand Sons warriors are dust-filled automata in power armour?", a = { "Scarab Occult", "Rubric Marines", "Khorne Berzerkers", "Noise Marines" }, correct = 1 },
		{ q = "Which World Eaters warriors are iconic chainaxe berserkers?", a = { "Plague Marines", "Rubric Marines", "Khorne Berzerkers", "Havocs" }, correct = 2 },
		{ q = "Which Emperor's Children warriors use sonic weaponry?", a = { "Chosen", "Raptors", "Warp Talons", "Noise Marines" }, correct = 3 },
		{ q = "Which plague is the signature supernatural disease of Nurgle?", a = { "Nurgle's Rot", "The Flayer Curse", "The Red Thirst", "The Black Rage" }, correct = 0 },
		{ q = "Which Thousand Sons sorcerer cast the Rubric?", a = { "Erebus", "Ahriman", "Typhus", "Lucius" }, correct = 1 },
		{ q = "Which Death Guard champion commands the Terminus Est?", a = { "Fabius Bile", "Lucius", "Typhus", "Kharn" }, correct = 2 },
		{ q = "Which Emperor's Children champion is cursed to return through those who take pride in killing him?", a = { "Ahriman", "Typhus", "Erebus", "Lucius the Eternal" }, correct = 3 },
		{ q = "Which ancient era saw humanity at its technological height?", a = { "Dark Age of Technology", "Age of Apostasy", "Age of Redemption", "Nova Terra Interregnum" }, correct = 0 },
		{ q = "Which era followed the collapse of Warp travel and isolated human worlds?", a = { "Great Crusade", "Age of Strife", "Indomitus Crusade", "Age of Apostasy" }, correct = 1 },
		{ q = "Which campaign reunited many human worlds under the Emperor before the Heresy?", a = { "Macharian Crusade", "Sabbat Worlds Crusade", "Great Crusade", "Damocles Crusade" }, correct = 2 },
		{ q = "Which current era is marked by the galaxy split by the Great Rift?", a = { "Age of Terra", "Age of Strife", "Time of Ending", "Era Indomitus" }, correct = 3 },
		{ q = "Which massive Warp storm split the galaxy after the fall of Cadia?", a = { "Cicatrix Maledictum", "Maelstrom", "Eye of Terror", "Hadex Anomaly" }, correct = 0 },
		{ q = "Which long-standing Warp rift was home to many Traitor Legion strongholds?", a = { "Hadex Anomaly", "Eye of Terror", "Storm of the Emperor's Wrath", "Screaming Vortex" }, correct = 1 },
		{ q = "Which Warp storm is a major pirate and renegade haven near Badab?", a = { "Cicatrix Maledictum", "Eye of Terror", "Maelstrom", "Webway" }, correct = 2 },
		{ q = "Which side of the Imperium is cut off from Terra by the Great Rift?", a = { "Segmentum Solar", "Imperium Sanctus", "Ultima Segmentum", "Imperium Nihilus" }, correct = 3 },
		{ q = "Which side of the Imperium still has clearer access to the Astronomican?", a = { "Imperium Sanctus", "Imperium Nihilus", "Halo Stars", "Ghoul Stars" }, correct = 0 },
		{ q = "Which Primarch returned in the Era Indomitus after Guilliman?", a = { "Jaghatai Khan", "Lion El'Jonson", "Ferrus Manus", "Sanguinius" }, correct = 1 },
		{ q = "Which crusade was launched by Guilliman after his return?", a = { "Macharian Crusade", "Sabbat Worlds Crusade", "Indomitus Crusade", "Angevin Crusade" }, correct = 2 },
		{ q = "Which new Space Marines were introduced by Belisarius Cawl?", a = { "Thunder Warriors", "Grey Knights", "Custodian Guard", "Primaris Space Marines" }, correct = 3 },
		{ q = "Which Archmagos was central to creating Primaris Space Marines?", a = { "Belisarius Cawl", "Arkhan Land", "Kelbor-Hal", "Sota-Nul" }, correct = 0 },
		{ q = "Which Space Marine reinforcement program sent Primaris warriors to many Chapters?", a = { "Abyssal Muster", "Ultima Founding", "Damocles Gulf Crusade", "Badab Reforging" }, correct = 1 },
		{ q = "Which holy Terran machine keeps the Emperor alive?", a = { "Astronomican Choir", "Noosphere", "Golden Throne", "Pharos Beacon" }, correct = 2 },
		{ q = "Which Imperial project tried to create a human Webway route?", a = { "The Rubric", "The Cadian Gate", "The Dolmen Gate", "The Imperial Webway Project" }, correct = 3 },
		{ q = "Which ancient race is credited with creating the Webway?", a = { "Old Ones", "Necrontyr", "Tau", "Krork" }, correct = 0 },
		{ q = "Which ancient engineered greenskin species are linked to the Orks?", a = { "Jokaero", "Krork", "Hrud", "Slaugth" }, correct = 1 },
		{ q = "Which ancient species fought the Necrontyr and C'tan in the War in Heaven?", a = { "Tau", "Kroot", "Old Ones", "Tyranids" }, correct = 2 },
		{ q = "Which Aeldari death-god prophecy is tied to the Rhana Dandra?", a = { "The Great Work", "The Long War", "The Octarius War", "The final battle of the Eldar gods" }, correct = 3 },
		{ q = "Which Imperial planet is the Throneworld?", a = { "Terra", "Mars", "Macragge", "Armageddon" }, correct = 0 },
		{ q = "Which planet is the capital of Ultramar?", a = { "Nocturne", "Macragge", "Baal", "Chogoris" }, correct = 1 },
		{ q = "Which world is famous for the massive wars against Orks and Chaos?", a = { "Tallarn", "Mordia", "Armageddon", "Valhalla" }, correct = 2 },
		{ q = "Which world is the home of the Space Wolves?", a = { "Nocturne", "Medusa", "Deliverance", "Fenris" }, correct = 3 },
		{ q = "Which moon-world is the Raven Guard's home?", a = { "Deliverance", "Chogoris", "Inwit", "Baal Secundus" }, correct = 0 },
		{ q = "Which world is the home of the White Scars?", a = { "Fenris", "Chogoris", "Nocturne", "Medusa" }, correct = 1 },
		{ q = "Which world is the home of the Salamanders?", a = { "Macragge", "Baal", "Nocturne", "Caliban" }, correct = 2 },
		{ q = "Which world was the destroyed home of the Dark Angels?", a = { "Prospero", "Nuceria", "Olympia", "Caliban" }, correct = 3 },
	}

local QUIZ_TOTAL = 10

local QuizGame = {}
QuizGame.__index = QuizGame

function QuizGame:new()
    local g = setmetatable({
        _questions = {},
        _current_q = 0,
        _selected = 0,
        _score = 0,
        _state = "idle",
        _last_correct = nil,
        _show_feedback = false,
        _on_correct = nil,
        _on_wrong = nil,
    }, QuizGame)
    return g
end

function QuizGame:start()
    local pool = {}
    for i = 1, #ALL_QUESTIONS do
        pool[i] = i
    end
    for i = #pool, 2, -1 do
        local j = math_random(i)
        pool[i], pool[j] = pool[j], pool[i]
    end

    self._questions = {}
    for i = 1, QUIZ_TOTAL do
        local src = ALL_QUESTIONS[pool[i]]

        local indices = { 1, 2, 3, 4 }
        for j = 4, 2, -1 do
            local k = math_random(j)
            indices[j], indices[k] = indices[k], indices[j]
        end

        local shuffled_answers = {}
        local new_correct = nil
        for j = 1, 4 do
            local old_idx = indices[j]
            shuffled_answers[j] = src.a[old_idx]
            if old_idx - 1 == src.correct then
                new_correct = j - 1
            end
        end

        self._questions[i] = {
            q = src.q,
            a = shuffled_answers,
            correct = new_correct,
        }
    end

    self._current_q = 1
    self._selected = 0
    self._score = 0
    self._state = "playing"
    self._last_correct = nil
    self._show_feedback = false
end

function QuizGame:score() return self._score end
function QuizGame:total() return QUIZ_TOTAL end
function QuizGame:is_game_over() return self._state == "done" end
function QuizGame:state() return self._state end
function QuizGame:current_index() return self._current_q end
function QuizGame:selected() return self._selected end
function QuizGame:last_correct() return self._last_correct end
function QuizGame:is_showing_feedback() return self._show_feedback end

function QuizGame:set_correct_callback(fn)
	self._on_correct = fn
end

function QuizGame:set_wrong_callback(fn)
	self._on_wrong = fn
end

function QuizGame:current_question()
    if self._current_q < 1 or self._current_q > QUIZ_TOTAL then
        return nil
    end
    return self._questions[self._current_q]
end

function QuizGame:select_up()
    if self._state ~= "playing" or self._show_feedback then return end
    self._selected = (self._selected - 1) % 4
end

function QuizGame:select_down()
    if self._state ~= "playing" or self._show_feedback then return end
    self._selected = (self._selected + 1) % 4
end

function QuizGame:confirm()
    if self._state ~= "playing" then return end
    if self._show_feedback then
        self._show_feedback = false
        self._last_correct = nil
        self._selected = 0
        self._current_q = self._current_q + 1
        if self._current_q > QUIZ_TOTAL then
            self._state = "done"
        end
        return
    end

    local q = self._questions[self._current_q]
    if not q then return end
    self._last_correct = (self._selected == q.correct)
    if self._last_correct then
        self._score = self._score + 1
        if self._on_correct then self._on_correct() end
    else
        if self._on_wrong then self._on_wrong() end
    end
    self._show_feedback = true
end

function QuizGame:update(dt)
    if self._state == "done" then return end
end

return QuizGame
